### ISSUE TITLE
103페이지 은전한닢 사용자 사전

### ISSUE THREAD

**Issue by joyhong85** [ratsgo/embedding#102]
안녕하세요
쓰신 책 잘 보고 있습니다.
보던 중에 103페이지 은전한닢 사용자 사전 추가 부분에서 예시로 보여주신 가우스전자는 종성유무가 F가 되어야 할 듯 한데요
한번 확인해 주시겠어요?
지식을 나눠주셔서 감사합니다~

**Comment by ratsgo** [comment]
@joyhong85 님 안녕하세요, 말씀하신 것처럼 종성유무를 F로 고치는게 정확합니다.
해당 내용을 아래처럼 고쳐 정오표와 전자책 등에 반영하겠습니다.

```
가우스전자,,,,NNP,*,T,가우스전자,*,*,*,*,*
서울대입구역,,,,NNP,*,T,서울대입구역,*,*,*,*,*
```

> 

```
가우스전자,,,,NNP,*,F,가우스전자,*,*,*,*,*
서울대입구역,,,,NNP,*,T,서울대입구역,*,*,*,*,*
```

꼼꼼하게 읽어주셔서 진심으로 감사드립니다.

**Comment by ratsgo** [comment]
한편 다음은 은전한닢 사용자 사전에 대해 추가적으로 궁금해 하실 독자들을 위해 기록용으로 남겨 둡니다.

- 사용자 사전 관련 공식 공지사항 : http://eunjeon.blogspot.com/2014/03/blog-post.html
- 사용자 사전 스키마 공지 (사전 형식 v.1.6) : https://docs.google.com/spreadsheets/d/1-9blXKjtjeKZqsf4NzHeYJCrr49-nXeRF6D80udfcwY/edit#gid=6
- 사용자 사전 스키마 (사전 형식 v.1.6) : 0은 아무것도 입력하지 않는다는 뜻

```
표층형, 0, 0, 0, 품사 태그, 의미 부류, 종성 유무, 읽기, 타입, 첫번째 품사, 마지막 품사, 원형, 인덱스 표현
```
- **종성 유무** : 읽기 마지막 글자에 종성이 있는지 없는지- T or F
