### ISSUE TITLE
bert fine-tune 에러

### ISSUE THREAD

**Issue by ldahee** [ratsgo/embedding#105]
bert 파인튜닝을 실행하기 위해 sentmodel.sh 파일의 171번째에 있는 명령어를 실행하면 에러가 뜹니다.
![image](https://user-images.githubusercontent.com/41093239/90468104-c19ac380-e150-11ea-91ce-fb2da4182d79.png)

아래는 발생한 에러와 해당 경로의 파일 목록 입니다.
![image](https://user-images.githubusercontent.com/41093239/90468226-176f6b80-e151-11ea-816b-c5efde6e255f.png)
![image](https://user-images.githubusercontent.com/41093239/90468147-e000bf00-e150-11ea-86e6-77a5976727b3.png)

혹시 pre-trian 과정에서 문제가 있었던 것 일까요?

**Comment by ldahee** [comment]
파인튜닝 실행하는 명령어에서 pretrain_model_fname 값을 bert_model.ckpt이 아니라 model.ckpt-100000로 변경하니 에러가 발생하지 않습니다. 감사합니다!

**Comment by ratsgo** [comment]
@ldahee 님 안녕하세요, 답이 너무 늦었는지 모르겠네요.
스샷으로 보여주신 해당 디렉토리를 보니 pretrained model 체크포인트가 없어서 생기는 에러로 보이는데요.
`bash sentmodel.sh download-pretrained-bert`를 실행하고 프리트레인 완료된 BERT를 다운받으면 다음과 같은 파일 목록이 보여야 합니다.

<img width="600" alt="스크린샷 2020-10-12 오후 1 55 58" src="https://user-images.githubusercontent.com/26211652/95706788-d1d3a880-0c92-11eb-9538-f99b35d607db.png">

한편 만일 스샷에 있는 `model.ckpt-100000`로 파인튜닝을 한다면 해당 체크포인트에서 파인튜닝을 시작하게 됩니다.
