### ISSUE TITLE
90쪽 soynlp 로컬 내려받기 관련

### ISSUE THREAD

**Issue by eomlocal** [ratsgo/embedding#107]
안녕하세요
오프라인환경에서 한국어임베딩책으로 학습하고 있는 사람입니다.
오프라인환경이기 때문에
"git pull origin master" 실행을 할 수 없는데요, 어떻게 해결할 수 있을까요?

나름 방법을 찾기 위해 soynlp-maser 를 전체 zip 으로 다운받아서 로컬PC에 옮겨두었습니다.
하지만 코드 3-11 '네이버 영화 리뷰 전처리코드'에서
corpus_fanme = ~ /ratings.txt  와 ~/ preprocessed_ratings.txt 가 없더라고요..

도움을 부탁드립니다. 감사합니다.

**Comment by ratsgo** [comment]
@eomlocal 님 부족한 책인데 관심 가져주셔서 감사드립니다.

> "git pull origin master" 실행을 할 수 없는데요, 어떻게 해결할 수 있을까요?

본 도서에서 제공하는 모든 스크립트는 도커 컨테이너(도서 1.4장 개발환경 설정)에서 실행하는 걸 전제로 짜여진 코드입니다.
말씀주신 git pull 명령어가 실행되지 않는 것은 git 도구가 로컬에 설치되지 않았기 때문으로 보이는데요.
@eomlocal 님 환경(윈도우 혹은 우분투, 맥 등)에 맞게 git 도구를 설치하셔야 할 것 같습니다(`git 설치`로 검색하면 많은 팁들이 있습니다).

> corpus_fanme = ~ /ratings.txt 와 ~/ preprocessed_ratings.txt 가 없더라고요..

코드 3-11 수행을 위해서는 코드 3-10 수행이 필요합니다. 위 말씀대로 git을 설치한 후 `git pull origin master`를 입력해 임베딩 리포의 모든 코드를 최신으로 업데이트 한 뒤 `bash preprocess.sh dump-raw-nsmc`을 실행하셔야 합니다.

도움이 되셨으면 좋겠습니다.
