### ISSUE TITLE
mecab 사용자사전에 대해서 질문드립니다

### ISSUE THREAD

**Issue by Younghun-Kwon** [ratsgo/embedding#108]
안녕하세요
저는 현재 한국어 임베딩 책을 구매하여 열심히 공부하고 있는 중입니다.
다름이 아니라 mecab 사용자사전을 등록한 후 실행을 해본 결과 
사용자사전보다 기존 사전이 우선순위가 높아 원하는 결과가 나오지 않고 있습니다.
사용하는 data는 띄어쓰기가 안되어있는 문장을 mecab을 이용해 형태소분석을 하고 있습니다.
사용자사전에 등록되어 있는 단어의 우선순위를 높게 만들고 싶은데 어떻게 하면 될까요?

**Comment by ratsgo** [comment]
해당 이슈는 mecab을 개발한 은전한닢 프로젝트에 문의하시는 게 좋을 것 같습니다.
해당 프로젝트의 주소는 다음과 같습니다.

- http://eunjeon.blogspot.com

관련해서 사용자 사전 우선순위에 대해 해당 프로젝트의 Q&A 게시판을 찾아본 결과 참고할 만한 주소를 공유해 드립니다.

- https://groups.google.com/g/eunjeon/c/ZD004KVPWC4/m/q4df98paEuEJ

도움이 되셨으면 좋겠습니다.
