### ISSUE TITLE
Window 10 개발환경

### ISSUE THREAD

**Issue by nateray42** [ratsgo/embedding#110]
안녕하세요.

환경이 여의치 않아서 윈도우 10으로 개발환경을 만들고 있는 학생입니다.

아마존 AWS에서 쓰기엔 요금 부담이 있어, Conda에서 가상환경을 만들었는데,

혹시 CUDA 지원이 가능한 Tensorflow 2 나 Pytorch 를 사용하면 책의 예제를 배우는 데 지장이 있을까요?

**Comment by nateray42** [comment]
아, 윈도우에서도 Windows Insider Version 20206 부터 WSL2 기반 nvidia-docker 가 가능한 듯 합니다.

https://docs.nvidia.com/cuda/wsl-user-guide/index.html

여기 참고해서 개발환경 만들었습니다. 참고해주세요~

**Comment by ratsgo** [comment]
> 안녕하세요.
> 
> 환경이 여의치 않아서 윈도우 10으로 개발환경을 만들고 있는 학생입니다.
> 
> 아마존 AWS에서 쓰기엔 요금 부담이 있어, Conda에서 가상환경을 만들었는데,
> 
> 혹시 CUDA 지원이 가능한 Tensorflow 2 나 Pytorch 를 사용하면 책의 예제를 배우는 데 지장이 있을까요?

@nateray42 님 안녕하세요. 답이 너무 늦었네요.
본 도서에서 제공하는 모든 스크립트는 Tensorflow 1.12에서 작동하도록 개발됐습니다.
텐서플로 버전을 올리거나 파이토치로 스크립트를 짜는 것은 전체 코드를 처음부터 개발해야 하는 것이어서 당장은 지원이 어려울 것 같습니다.
도움이 되지 못해 송구스럽네요.

**Comment by ratsgo** [comment]
> 아, 윈도우에서도 Windows Insider Version 20206 부터 WSL2 기반 nvidia-docker 가 가능한 듯 합니다.
> 
> https://docs.nvidia.com/cuda/wsl-user-guide/index.html
> 
> 여기 참고해서 개발환경 만들었습니다. 참고해주세요~

팁 공유 감사드립니다!
