### ISSUE TITLE
정오표 페이지 표기 관련 (3쇄)

### ISSUE THREAD

**Issue by cogscired** [ratsgo/embedding#111]
https://ratsgo.github.io/embedding/notice.html

의 

> P. 62
> 
> TF-IDF 행렬 구축 튜토리얼은 4.1절, '잠재 의미 분석'에서 설명한다.
> ...

부분은 3쇄 책에서는 P. 64 로 확인 되는것 같습니다.

**Comment by cogscired** [comment]
> P. 72
> 
> 언어학자들이 제시하는 품사 분류 기준은 기능(function), 의미(meaning), 형태(form) 등 세 가지다. 
> > 
> 학교문법에 따르면 품사 분류 기준은 기능(function), 의미(meaning), 형식(form) 등 세 가지다.

부분도 P. 74 로 확인 되는것 같습니다.

**Comment by ratsgo** [comment]
@cogscired 님 날카로운 지적 감사드립니다. 에이콘출판 편집팀과 공동으로 작업해 정오표에 각 쇄별 페이지수 정보를 반영해 두었습니다. 다시 한번 관심에 감사드립니다!
