### ISSUE TITLE
p.128 코드 4-3 Word2Vec Skip-Gram 모델 학습 관련 질문드립니다.

### ISSUE THREAD

**Issue by geniusseok11** [ratsgo/embedding#112]
CPUs: 8, RAM: 16GiB
Nvidia 940mx, i7 6세대, Ubuntu 20.04 환경에서 
저자께서 제공해주신 본 책의 gpu docker image를 실행시켜 학습을 진행하고 있습니다.

p.128 코드 4-3이 Word2Vec Skip-Gram 모델 학습 python 코드인데요.
이 코드를 실행하면 자꾸 docker container가 죽는 상황이 발생합니다.

혹시 어떤 부분 때문에 이러한 상황이 지속적으로 발생하는 것인지 궁금합니다.

*) GPU 없는 i7 8세대, RAM 16GiB, Windows 10 환경에서 cpu docker image로도 진행해보았으나 동일 현상 발생하였습니다.

도움 부탁드립니다.
감사합니다.

**Comment by geniusseok11** [comment]
#106에 남겨주신 코드를 통해 정상적으로 실행하였고 저도 약 1시간 정도 소요되었습니다.
혹시 원 코드는 어느 정도의 메모리가 필요한가요?
저자님의 컴퓨터의 그래픽 카드, RAM, CPU 등의 사양에 대해 알 수 있을까요?

**Comment by ratsgo** [comment]
@geniusseok11 님 질문해 주셔서 감사드립니다. #106 코드를 실행한 결과 잘 실행됐다니 다행입니다. 관련 코드는 마스터에 반영해 두었습니다.
저도 우분투 환경에서 진행했고요, 램이 64GB 정도로 넉넉했던 것 같습니다. GPU는 1080ti였습니다. 실험한 지 너무 오래되어서 다른 스펙이 정확히 기억나지 않는 점 양해 부탁드립니다.
앞으로는 리소스가 적은 환경에서도 잘 동작할 수 있도록 세심하게 신경쓰겠습니다. 감사합니다.
