### ISSUE TITLE
Swivel (코드 4-30) 관련

### ISSUE THREAD

**Issue by cogscired** [ratsgo/embedding#114]
> 코드 4-30 Sivel 모델 학습 `bash` (P 152)

수행시 `models/swivel/fastprep` 가 없는 경우,

`models/swivel` 에서

`make -f fastprep.mk`

수행 후 진행 할 수 있었습니다.

(fastprep.mk 파일에 레퍼런스가 있긴 한데, 저처럼 잘 못찾는 분들을 위해 ...)

**Comment by ratsgo** [comment]
답변이 너무 늦었네요. 해당 파일의 경우 도서에 제시된 도커 환경에 존재하기는 합니다.

<img width="500" alt="스크린샷 2020-10-12 오후 12 58 17" src="https://user-images.githubusercontent.com/26211652/95704069-a8af1a00-0c8a-11eb-80f7-363f63137d6b.png">

따라서 도커 환경에서 사용하실 경우 해당 에러가 발생하지 않고요.
로컬 환경에서 사용하실 경우 @cogscired 님께서 말씀해주신 것처럼 진행하시면 됩니다.
다른 분들을 위해 이렇게 팁을 공유해주셔서 감사드립니다.
