### ISSUE TITLE
p.241 코드 5-42 BERT model pre-training에 대해 질문드립니다.

### ISSUE THREAD

**Issue by geniusseok11** [ratsgo/embedding#116]
log 파일을 살펴보면 5분간 동작하다가 

"OP_REQUIRES failed at assign_op.h:117 : Resource exhausted: OOM when allocating tensor with shape[768] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
INFO:tensorflow:Error recorded from training_loop: OOM when allocating tensor with shape[768,768] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node bert/encoder/layer_2/attention/self/key/kernel/adam_m/Assign (defined at /notebooks/embedding/models/bert/optimization.py:122)  = Assign[T=DT_FLOAT, _grappler_relax_allocator_constraints=true, use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](bert/encoder/layer_2/attention/self/key/kernel/adam_m, bert/encoder/layer_0/attention/output/dense/kernel/adam_m/Initializer/zeros)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Caused by op 'bert/encoder/layer_2/attention/self/key/kernel/adam_m/Assign'"

"ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[768,768] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node bert/encoder/layer_2/attention/self/key/kernel/adam_m/Assign (defined at /notebooks/embedding/models/bert/optimization.py:122)  = Assign[T=DT_FLOAT, _grappler_relax_allocator_constraints=true, use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](bert/encoder/layer_2/attention/self/key/kernel/adam_m, bert/encoder/layer_0/attention/output/dense/kernel/adam_m/Initializer/zeros)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info."

위의 오류 메시지들 등장 이후 동작이 멈추는 것으로 확인됩니다.

사양은 Intel® Core™ i7-6700HQ CPU @ 2.60GHz × 8 , GeForce 940MX, Ubuntu 20.04.1 LTS, 64-bit, RAM memory 16GB, Swap partition size 20GB, NVIDIA driver 435, CUDA 10.1입니다.

이 문제를 해결하고 정상적으로 pre-training하려면 어떻게 조치를 취해야 하나요?
p.242 코드 5-43의 자동화 스크립트도 실행하였지만 동일한 오류 발생하며 동작이 멈췄습니다.

로그 파일을 첨부합니다.
감사합니다.

[bert-pretrain.log](https://github.com/ratsgo/embedding/files/5337625/bert-pretrain.log)

**Comment by ratsgo** [comment]
@geniusseok11 님 안녕하세요. 해당 메세지들은 아무래도 GPU 메모리 문제로 보이는데요. GeForce 940MX보다 더 큰 메모리를 가진 GPU를 사용해야 할 것 같습니다.
우회하는 방법이 하나 더 있을 것 같은데요. 5-43의 자동화 스크립트를 실행하면 BERT 파인튜닝을 위해 `models/tune_utils.py`에서 `BERTTuner`라는 클래스를 사용합니다. 여기에서 `max_seq_length`가 기본값으로 128로 잡혀 있는데요. 이를 적당한 크기(32 혹은 64)로 줄이면 파인튜닝에 필요한 메모리 양을 줄일 수 있을 것 같습니다. `max_seq_length`는 BERT 레이어가 최대로 처리하는 토큰 수 기준 길이입니다.

- https://github.com/ratsgo/embedding/blob/8f805859843551efccd5be0910ff0c592ad8d417/models/tune_utils.py#L434

**Comment by ratsgo** [comment]
예컨대 `max_seq_length`를 줄이려면 `BERTTuner`를 선언할 때 다음과 같이 해주면 됩니다.

```python
model = BERTTuner(train_corpus_fname=args.train_corpus_fname,
                                   test_corpus_fname=args.test_corpus_fname,
                                   vocab_fname=args.vocab_fname,
                                   pretrain_model_fname=args.pretrain_model_fname,
                                   bertconfig_fname=args.config_fname,
                                   model_save_path=args.model_save_path,
                                   max_seq_length=32,
)
```
