### ISSUE TITLE
p209 그림 5-16의 컨볼루션 필터의 크기에 대해서 문의합니다

### ISSUE THREAD

**Issue by HyeonminNam** [ratsgo/embedding#119]
안녕하세요.
먼저 '한국어 임베딩'이라는 좋은 책을 써주셔서 감사하다는 말씀드리고 싶습니다.
'한국어 임베딩' 책으로 자연어 처리 공부를 하는 학생 중 한명입니다.

문의드린 것은 p209의 그림 5-16의 필터 크기 때문인데요.
책에서는 컨볼루션 필터의 크기를 '2 X 문자 임베딩의 차원 수'라고 언급하고 있고,
p208에서 필터가 보는 대상을 '<BOW>, 밥1'과 '밥1, 밥2'라고 하고 있습니다.

그러나 그림 5-16에서는 필터가 '<BOW>, 밥1, 밥2', '밥1, 밥2, 밥3'을 보고 있는 것처럼 보여서 혹시 그림이 잘못 그려진 것인지 여쭤보고자 문의드렸습니다.

감사합니다.

**Comment by ratsgo** [comment]
@HyeonminNam 님 질문 감사드립니다. 언급하신 내용이 맞습니다. 그림이 맞다면 '3 X 문자 임베딩의 차원 수'가 되는 것이 정확한 것 같습니다. 섬세하게 읽어주셔서 감사드립니다. 정오표에도 반영해 두겠습니다!
