### ISSUE TITLE
책 127페이지 중 "from models import WordEmbeddingEvaluator " 문의 

### ISSUE THREAD

**Issue by taijinkim** [ratsgo/embedding#120]
안녕하세요 
해당 책 구매하여 잘 읽었습니다 감사합니다

다름이 아니오라 
from models import WordEmbeddingEvaluator
를 실행하려면 models 라이브러리를 확인해야 하는데 
pypi 에서 있는 https://pypi.org/project/models/ 를 들어가봐도 관련된 라이브러리 파일을 찾을수 없어서
해당 라이브러리를 다운로드 받으려면 어떻게 해야 하는건가 해서요 

확인말씀 부탁드립니다 감사합니다 
(며칠째 시도하고 있는데 잘 모르겠습니다 ㅠㅜ)

**Comment by ratsgo** [comment]
안녕하세요 @taijinkim 님, 너무 늦게 답을 드린 건 아닌지 모르겠네요.
해당 코드를 실행하려면 본 저장소(`embedding`)가 로컬에 있어야 합니다.
다음을 실행하시면 본 저장소를 로컬에 내려받을 수 있습니다.
(단 이렇게 내려받을 경우 FastText 등 일부 튜토리얼은 수행할 수 없습니다)

```
git clone https://github.com/ratsgo/embedding.git
``` 

도서의 서론, 개발환경 설정에서 안내된 도커 이미지를 사용하시면 도서의 모든 튜토리얼을 수행할 수 있으니 참고하시면 좋겠습니다.
