### ISSUE TITLE
책의 코드 4-8 (FastText Skip-gram 모델 학습) 문의

### ISSUE THREAD

**Issue by capvirus73** [ratsgo/embedding#121]
안녕하세요.
작년에 책을 구매하고, 이제 소스 코드들을 실행보고 있습니다. 

아래 코드 4-8을 실행하려고 하니 에러가 발생합니다.
models/fastText/fasttext skipgram -input data/tokenized/corpus_mecab.txt -output data/word-embeddings/fasttext/fasttext

git에서 해당 모델 폴더가 없는 것 같습니다.
확인 부탁드립니다.
감사합니다.

**Comment by ratsgo** [comment]
@capvirus73 님 질문 주셔서 감사합니다.
도서에 있는 스크립트는 도커 컨테이너에서 수행하는 걸 전제로 제시된 것입니다. 
해당 컨테이너는 도서 튜토리얼의 모든 코드가 정상 작동할 수 있도록 의존성 패키지를 모두 설치한 환경입니다.
@capvirus73 님께서는 도커 컨테이너를 사용하지 않고 별도의 환경을 구축해 사용하고 계시는 것으로 보이는데요.
FastText 환경 설치를 위해선 다음 이슈를 참고하시면 좋겠습니다.

https://github.com/ratsgo/embedding/issues/56
