### ISSUE TITLE
도서에 나온 python 코드 찾는 법

### ISSUE THREAD

**Issue by ksuplee** [ratsgo/embedding#122]
2장까지는 내용이 얼마되지 않아 직접 입력을 해서 해결했습니다.

3장에 있는 코드 3-2 (p.81)부터 나름대로 긴 python 코드를 찾는데 repository를 다 찾아 보았는데 찾을 수가 없습니다. 도서에는 분명 repository와 튜토리얼 페이지에 있다고 했는데요. 

도움을 요청합니다. 감사합니다.

**Comment by ratsgo** [comment]
@ksuplee 님 안녕하세요, 질문해주셔서 감사합니다.
3-2 코드는 다른 코드와 달리 예시를 위해 책 본문에만 넣은 것인데요.
거의 유사한 동작을 하는 코드는 우리 저장소(`embedding`)의 다음 위치에서 찾을 수 있습니다.

https://github.com/ratsgo/embedding/blob/da472056577c1f7ca2f91c5426495381c697e812/preprocess/dump.py#L10 

한편 도서 예시 코드 가운데 특정 키워드로 아래와 같이 검색하면(웹 화면 최상단에 검색창이 있습니다) 해당 코드를 좀 더 쉽게 찾아보실 수 있을 것 같습니다.

<img width="600" alt="스크린샷 2020-12-06 오후 2 34 22" src="https://user-images.githubusercontent.com/26211652/101272514-4bd66880-37d0-11eb-9949-2b25e71b4ddd.png">

**Comment by ksuplee** [comment]
빠르고 친절하신 답변 감사합니다.

**Comment by ksuplee** [comment]
빠르고 친절하신 답변 감사합니다.

한국어 임베딩에는 실제 현실에서 접한 프로젝트를 바탕으로 쓰신 것 같아 많은 도움이 되고 있습니다.
저는 spyder 또는 아나콘다를 이용하여 python을 겨우 실행하는 정도인데 docker가 적용되는
해결해야 할 문제가 많습니다.

1. spyer에서는 docker 환경을 적용할 방법이 마땅치 않습니다.
2. 아나콘다는 책의 안내에 따라 notebook까지는 조성하였는데 python 코드를 편집하고 실행하는 것이 마땅치 않습니다.
3. MS VSC를 설치하니 docker 연결이 가능합니다. ratsgo/embedding image를 연결을 시도했습니다.
    그런데 ID와 비밀번호를 물어보는데 registry만 연결하면 되는지요?
    아니면 VSC에서 책의 notebook 예제를 실행하고자 하면 어떠한 세팅이 필요한지요?
    너무 초보적인 질문을 드려 송구하면서 감사드립니다.

이길섭드림

2020년 12월 6일 (일) 오후 2:36, gichang.lee <notifications@github.com>님이 작성:

**Comment by ratsgo** [comment]
안녕하세요 @ksuplee 님 너무 늦게 답을 드려 죄송합니다.
해당 질문들은 제 지식 범위를 벗어난 것 같은데요. 
문제를 해결하셨거나 여전히 어려움을 겪고 계시다면, 
이 리포에 방문하는 여러분을 위해 별도 이슈를 작성해 주신다면 큰 도움이 될 것 같습니다.

다시 한번 부족한 책에 관심 가져주셔서 감사드립니다.
