### ISSUE TITLE
Docker 관련 문의입니다.

### ISSUE THREAD

**Issue by clock509** [ratsgo/embedding#124]
안녕하세요! 한국어 임베딩 책으로 NLP를 공부하고 있습니다.

현재 AWS가 아닌 GCP에 Ubuntu OS의 VM을 생성하여 SSH 접속을 한 후 
도커 컨테이너를 띄워서 책 내용을 실습하고 있습니다. 그런데, 제가 도커는 처음인지라 
질문을 한 가지 드리고 싶습니다.

다름이 아니라, 책 실습 후에 사용중이던 SSH를 종료하고 다시 접속하여 컨테이너를
띄워보면 하면, 이전까지 실습했던 내용들이 모두 사라져 있네요.  VM 인스턴스를 
중지하지 않는데도요. 

예를 들면, 컨테이너를 띄운 상태에서 파이썬 전처리 코드 파일을 작성하고, 전처리 완료된 
데이터셋이 확보된 걸 확인하고 SSH 접속을 종료한 후, 다음날 다시 SSH 접속해서
`docker run -it --rm ratsgo/embedding-cpu bash` 로 컨테이너를 다시 띄우면 전날 작업한
내용들이 다 사라져 있었습니다. ㅠㅠ 심지어 apt-get으로 설치한 패키지들도 지워져있고요.

SSH를 종료하고 재접속했을 때 이전에 하던 실습하던 내용들을 이어서 하고 싶은데, 방법이 없을까요?

**Comment by clock509** [comment]
방법을 찾아 문제 해결가 되었습니다. close 하겠습니다!!! :)

**Comment by sehee-jeong** [comment]
안녕하세요. @clock509 선생님, 혹시 어떻게 해결 하셨는지 여쭈어봐도 될까요 :)?

**Comment by clock509** [comment]
> 
안녕하세요, @sehee-jeong 선생님! 오래 기다리셨을 것 같은데 답변이 늦어 정말 죄송합니다ㅠㅠ

사실 꽤 오래 전에 했던 일이라 제가 명령어를 실행한 절차와 상황이 잘 기억이 나질 않습니다만,
도커 관련해서 검색해 보니 `--rm` 옵션이 '컨테이너를 종료하면 자동으로 삭제되도록 설정'하는 옵션이라고 합니다.
제 생각에는, SSH 접속을 종료하면서 의도치 않게 컨테이너도 종료되고, 그러면서 컨테이너가 삭제된 것이 아닐까 싶습니다.

답변이 너무 늦었지만 작게라도 도움이 되셨으면 좋겠습니다..!!
