### ISSUE TITLE
Swivel (코드4-30) 관련

### ISSUE THREAD

**Issue by clock509** [ratsgo/embedding#125]
안녕하세요. docker 환경에서 실습 코드를 돌리다가, 우분투 OS 로컬 환경에서 실습을 해 보고 있습니다.
(docker 환경으로 하면 잘 되지만, 향후 실시할 프로젝트에서 로컬 환경에서 할 것 같아서 미리 실습 중입니다...)

코드 4-30을 실행하던 도중, `fastprep` 쪽에서 `No such file or directory` 에러가 발생했습니다.

이에 #114 를 참고하여 `make -f fastprep.mk` 를 실행해 보았지만, 아래와 같은 에러가 발생하며 되지 않았습니다.
![20201228205102](https://user-images.githubusercontent.com/47171251/103212600-9752e100-494e-11eb-8e46-9f5186877c1d.png)

`make -f fastprep.mk` 실행 시 /tensorflow/core/example/ 디렉터리는 생성되지만, 위 이미지와 같은 에러가 발생하며
그 안에 파일이 생성되지는 않습니다. 혹시 이미지에 나온 에러는 무슨 에러인지 알 수 있을까요...?

p.s. 참고로 현재 우분투 OS 로컬 환경에 c나 c++ 관련 환경을 따로 설치/구축하지는 않았습니다. 혹시 그 때문일까요?

**Comment by ratsgo** [comment]
@clock509 님 안녕하세요, 답이 너무 늦었습니다. 죄송합니다.
해당 질문은 제 지식 범위를 벗어난 것 같네요ㅠㅠ 
혹시 이슈를 해결하셨는지요? 만약 그렇지 않다면 원 저자 여러분께 질문을 드리는 걸 권해드립니다.
다시 한번 도움이 못되드려 송구스럽습니다.
