### ISSUE TITLE
P116 수식 4-4

### ISSUE THREAD

**Issue by skymygo** [ratsgo/embedding#127]
해당책에서는 nplm 의 수식을 
b + Wx + U tanh(d + Hx) 로

교수님의 이전 블로그나 다른 블로그들에서는 
b + U • tanh(d + Hx)  로 되어있는데

제가 잘 모르겠어서 이슈로 알려드립니다

**Comment by ratsgo** [comment]
안녕하세요 @skymygo 님, 답이 너무 늦어 죄송합니다.
해당 파트는 요슈아 벤지오의 2003년 논문 [A Neural Probabilistic Language Model](https://www.jmlr.org/papers/volume3/bengio03a/bengio03a.pdf)을 정리한 내용인데요.
제가 책에 쓴 부분은 다음의 해당 논문 수식을 그대로 옮겨온 것입니다. 논문 7페이지입니다.

<img width="733" alt="스크린샷 2021-06-26 오후 12 35 48" src="https://user-images.githubusercontent.com/26211652/123500769-5debfb80-d67b-11eb-9baa-bd0fd51c352c.png">

참고가 되셨으면 좋겠습니다. 부족한 책인데 관심 가져주셔서 진심으로 감사드립니다.
