### ISSUE TITLE
page196 수식5-4 오타

### ISSUE THREAD

**Issue by hccho2** [ratsgo/embedding#129]
수식 5-4에서 가운데 식의 분자에 있는 첨자 k는 왼쪽(<img src="https://render.githubusercontent.com/render/math?math=p(z_{d,i}=j|z_{-i},w)">)에 등장하지 않습니다.
topic index라면 j라고 표시되어 있으니, 가운데 식의 분자에서 k가 j로 바뀌어야 할 것 같습니다.

**Comment by ratsgo** [comment]
@hccho2 님께는 늘 신세만 지는 것 같네요. 역시 날카로운 지적 감사드립니다.
말씀듣고 notation과 표를 수정해봤습니다. 

<img width="2309"  src="https://user-images.githubusercontent.com/26211652/133379547-f64a93ff-3c88-4e82-8088-8713927810e0.png">

@hccho2 님께서 의견 더 주시면 반영해서 정오표와 이후 판본에 반영하겠습니다.
다시 한번 감사드립니다.
