### ISSUE TITLE
수행 개발 환경을 공지해주시기 부탁드립니다. 

### ISSUE THREAD

**Issue by waltechel** [ratsgo/embedding#131]
- 제 생각에는 tensorflow 1.14 버전 정도가 되면 동작이 되는 것 같습니다.
- 코랩으로 해보고 있는데 코랩은 대개 2.x 대 버전의 tensorflow를 주게 되어요. 그래서 완전 초심자들에게는 지금 <한국어 임베딩>이 tensorflow 1.x 대 버전에서 동작하고 있는 것을 공지해야 한다고 생각합니다.
- 개발 환경을 readme 파일에 업데이트 하면 어떨까요?

**Comment by ratsgo** [comment]
네 동의합니다. [도커 이미지를 제공](https://github.com/ratsgo/embedding/blob/d9fd4ad3ce65c22372d0735d5b5674ed353c6ad9/docker/Dockerfile-GPU#L1)하고는 있으나 도커 없이 수행하는 분들도 있다는 생각이 드네요. 곧 README도 업데이트해 두겠습니다. 관심 가져주셔서 진심으로 감사드립니다.

**Comment by ratsgo** [comment]
다음과 같이 README를 업데이트하였습니다. 부족한게 많은데 관심 가져주셔서 진심으로 감사드립니다!

- https://github.com/ratsgo/embedding/commit/1c2a1c81f39879fe2f2edbcc14cec23500e37a90
