### ISSUE TITLE
코드를 파이토치 버전으로도 업로드 해주실 계획이 있나요?

### ISSUE THREAD

**Issue by hellojinwoo** [ratsgo/embedding#22]
안녕하세요. '한국어 임베딩'이라는 책에 관심이 생겨서 알아보고 있던 도중에 이 깃헙에 업로드 된 코드가 Tensorflow로 작성되어 있더라구요. 그런데 제가 TF를 볼줄 몰라서요. 

혹시 이 깃헙에 올라온 코드를 Pytorch 딥러닝 프레임워크로 컨버전해서도 업로드 해주실 수 있으실까요?

**Comment by ratsgo** [comment]
여력이 되는대로 커밋하겠습니다. 다만 재야의 무림 고수 분들의 Pull Request를 적극 환영합니다!

**Comment by ratsgo** [comment]
시간이 많이 경과하였으므로 이슈 클로즈합니다. 파이토치 프로젝트를 띄울 경우 별도 이슈로 관리하겠습니다.
