### ISSUE TITLE
안녕하세요! 책 내용과 관련해서 몇가지 이슈를 남겨봅니다.

### ISSUE THREAD

**Issue by graykode** [ratsgo/embedding#23]
안녕하세요!  책 내용과 관련해서 부족하지만, 제 개인 적인 생각을 담은 몇가지 이슈를 남겨봅니다.
먼저 들어가기 앞서서 평소에 이기창님의 [블로그](https://ratsgo.github.io) 글을 읽으며, 정말 많은 공부를 할 수 있었음에 진심으로 감사 인사를 드립니다 👍 👍 
더불어 깔끔한 목차, 설명과 한번에 이해되는 그림까지 담은 정말정말 좋은 책을 써주셔서 감사드리며, 어제부터 정독을 하고 있습니다

**P222**

*'Vaswani et al(2017)에 따르면 이 경우에 쿼리-키 내적 행렬의 분산을 줄이게 돼 개별 **소프트맥스 값이 지나치게 작아지는 것을 방지**'* 보다 ***소프트맥스 값이 지나치게 커지는 것을 방지*** 또는 ***소프트맥스의 그래디언트가 작아지는 것을 방지***가 더 올바르지 않을까라고 생각합니다

> We suspect that for large values of dk, the dot products grow large in magnitude, pushing the softmax function into regions where it has extremely small gradients (Vaswani at el, 2017) Attention is all you need.

**P228**

그림 5-27을 보면 3x3 행렬에서 i==j 일때, 0으로 마스킹된다고 그려져 있으나, MaskedMultiHead Attention의 [실제 구현 코드](https://github.com/tingkai-zhang/openai-gpt-pytorch/blob/d7211b97bf679d9ee3c1de099f6a76bf76a6ba22/model_pytorch.py#L74)를 보면, ***i==j일때도 마스킹하지 않습니다(0이 마스킹).***

![image](https://user-images.githubusercontent.com/10525011/65773751-d3a9f700-e177-11e9-82bc-6806bb509c69.png)

i==j일 때도 셀프 어텐션하되, Language Model을 만들기 위해(Next token Predict) 준비하는 부분이 [이 부분](https://github.com/tingkai-zhang/openai-gpt-pytorch/blob/d7211b97bf679d9ee3c1de099f6a76bf76a6ba22/model_pytorch.py#L185)의 영향을 많이 받는다고 생각합니다

**P230**

*전체 학습 데이터 토큰의 15%를 마스킹한다* 보다, ***학습 데이터 한 문장의 토큰의 15%를 마스킹한다***가 더 옳을 것 같습니다. 실제 **[google-research/bert](https://github.com/google-research/bert)** 코드를 보면 `create_masked_lm_predictions` 함수에 512 시퀀스 길이의 문장(즉, [CLS], A, [SEP], B, [SEP])가 들어오므로 [이 라인](https://github.com/google-research/bert/blob/0fce551b55caabcfba52c61e18f34b541aef186a/create_pretraining_data.py#L403)을 보면 ***학습 데이터 한 문장의 토큰의 15%를 마스킹하는 것***이 더 올바른 것 같습니다

논문에서도 `in each sequence at random` 이라는 표현이 붙습니다.

> In all of our experiments, we mask 15% of all WordPiece tokens in each sequence at random.

감사합니다 😄

**Comment by ratsgo** [comment]
안녕하세요, graykode님! 책을 정독해주시고 의견 남겨주셔서 진심으로 감사드립니다. @graykode  님 같은 열혈 독자 분들께 누가 되지 않도록 책을 열심히 썼는데 역시 부족한 부분이 많아서 부끄러운 마음뿐입니다.

P222와 P230에 관련해서는 @graykode 님 의견이 옳다고 생각합니다. 2판을 다음과 같이 수정해 두고 정오표에도 알리겠습니다. 곧 eBook도 출간 예정인데 eBook에는 바로 반영해두겠습니다.

- P222 : 개별 소프트맥스 값이 지나치게 작아지는 것을 방지 > 소프트맥스의 그래디언트가 작아지는 것을 방지
- P230 : 전체 학습 데이터 토큰의 15%를 마스킹한다 > 학습 데이터 한 문장의 토큰의 15%를 마스킹한다

P228과 관련해서 제가 알기로 GPT는 `START`와 `END` 토큰을 쓰는 걸로 아는데요. 두 토큰을 고려하면 다음과 같이 어텐션 마스크를 구성할 수 있을 것 같습니다(0이 마스킹, Label은 이번에 맞출 단어).

<img width="300" alt="KakaoTalk_Photo_2019-09-28-10-15-24" src="https://user-images.githubusercontent.com/26211652/65809521-e99bd400-e1d8-11e9-8ccd-24bde3e7cfa4.png">


`START`, `END` 토큰을 생략하고 그린다면 다음과 같이 어텐션 마스크를 구성할 수 있을 것 같습니다(독자들의 이해를 수월하게 하기 위해 `START`, `END` 토큰을 생략한 아래 그림을 책에 넣었습니다).

<img width="270" alt="KakaoTalk_Photo_2019-09-28-10-15-10" src="https://user-images.githubusercontent.com/26211652/65809537-10f2a100-e1d9-11e9-9bde-8776c919516b.png">

위 두 가지 경우 모두 모델이 맞춰야할 토큰 이후 정보(예컨대 `보다`를 맞춰야할 때 `꿈`만 참고, `해몽`을 맞춰야할 때 `꿈`, `보다`만 참고)를 가린다는 점에서 같다고 생각합니다.

혹시 제가 잘못 알고 있거나 첨언하실 부분 있으시면 언제든지 말씀해주세요. 부족한 책인데 관심 가져주셔서 다시 한번 감사드린다고 말씀드리고 싶어요!

**Comment by graykode** [comment]
@ratsgo  안녕하세요! 
공식적인 구현은 아니지만 openai-gpt-pytorch 구현(https://github.com/tingkai-zhang/openai-gpt-pytorch)을 보고 제 생각을 말씀드리겠습니다! 


![image](https://user-images.githubusercontent.com/10525011/66111024-f36f6e00-e602-11e9-8afc-262c53174410.png)

<img width="280px" src="https://user-images.githubusercontent.com/10525011/66110676-3a109880-e602-11e9-9c0f-ddd50fa5c63b.png">

먼저 전체적인 구조를 간략하게 그리면 위와 같습니다.
위 예제는 BERT와 조금 비슷하게 GPT에서 이어지는 문장 ([start] + x1 + [delimiter] + x2 + [cls])과 이어지지 않는 문장([start] + x1 + [delimiter] + x3 + [cls])을 나열하고 둘을 입력으로 넣은후 Language Model과 Classification loss를 더해서 학습시키는 방식입니다.
```python
# Language modeling loss
if lm_logits is not None:
    x_shifted = X[:, :, 1:, 0].contiguous().view(-1)  # Shape: 252
    M = M.view(-1, M.size(2))
    lm_losses = self.lm_criterion(lm_logits, x_shifted)
    lm_losses = lm_losses.view(X.size(0) * X.size(1), X.size(2) - 1)
    lm_losses = lm_losses * M[:, 1:]
    lm_losses = lm_losses.sum(1) / torch.sum(M[:, 1:], 1)
# Classification loss
clf_losses = self.clf_criterion(clf_logits, Y)
if only_return_losses:
    return (clf_losses, lm_losses) if lm_logits is not None else clf_losses

if self.lm_coef > 0 and lm_logits is not None:
    train_loss = clf_losses.sum() + self.lm_coef * lm_losses.sum()
```

XMB는 input이고 [8(batch_size), 2(0번 인덱스는 이어지는 문장, 1번 인덱스는 이어지지 않는 문장), 시퀀스 길이]
이 XMB를 Transformer 입력으로 넣어서 [16, 77(시퀀스 길이), 768(임베딩 dimension)]을 만들고 
```python
def forward(self, h):
    # Truncated Language modeling logits (we remove the last token)
    h_trunc = h[:, :-1].contiguous().view(-1, self.n_embd)
    lm_logits = self.decoder(h_trunc)
    return lm_logits
```

이렇게 만든 Language Model loss를 아래 코드에서 계산합니다. 따라서 이 부분이 **P(x_{2:77}|x_{1:76})**으로 기존 RNN처럼 Language Model을 만들어주는 부분이라고 생각합니다.
```python
x_shifted = X[:, :, 1:, 0].contiguous().view(-1)  # Shape: 252
M = M.view(-1, M.size(2))
lm_losses = self.lm_criterion(lm_logits, x_shifted)
```

따라서 Self-Attention 시에는 아래 코드와 같이 Masking을 하는데 위에서 말씀하셨던 것처럼 **i==j이 마스킹이 되지 않는 것이 아니라 어텐션이 된다고 생각합니다!**
```python
self.register_buffer('b', torch.tril(torch.ones(n_ctx, n_ctx)).view(1, 1, n_ctx, n_ctx))

def _attn(self, q, k, v):
    w = torch.matmul(q, k)
    if self.scale:
        w = w / math.sqrt(v.size(-1))
    w = w * self.b + -1e9 * (1 - self.b)  # TF implem method: mask_attn_weights
    w = nn.Softmax(dim=-1)(w)
    w = self.attn_dropout(w)
    return torch.matmul(w, v)
```

결론적으로 Language Modeling을 말씀하신 것 처럼 P(꿈) + P(보다|꿈) + P(해몽|보다, 꿈) 이렇게 어텐션에서 만드는 것이 아닌 P(x_{2:77}|x_{1:76})와 같은 방식으로 만드는 것이 좀 더 맞다고 생각합니다 :D

**Comment by ratsgo** [comment]
안녕하세요, @graykode 님! 부족한 책인데 이렇게 상세히 이슈를 남겨주시니 감사할 따름입니다. 두 가지를 명확히 하고자 하는데요. 의견 남겨주시면 큰 도움이 될 것 같습니다. 물론 어디까지나 제 지식 범위 내에서 말씀드리는 거라 잘못된 점이나 첨언하실 게 있으시면 편히 말씀해 주세요.

**self-attention 관련**
공유해 주신 GPT 코드는 확인해 보니 말씀 주셨던 것처럼 **i==j인 경우 어텐션이 됩니다**. 다만 이번 논의의 핵심은 이번 레이블 단어를 예측할 때 해당 레이블 단어를 참고하는지 여부라고 생각하는데요. GPT 코드를 보면 레이블, 즉 `target`(`x_shifted`)이 입력 단어 시퀀스를 한 칸씩 뒤로 시프트한 것이기 때문에,  `보다`를 맞춰야할 때 `꿈`만 참고, `해몽`을 맞춰야할 때 `꿈, 보다`만 참고한다는 생각이 듭니다. @graykode 님도 같은 생각이신지 여쭙고 싶습니다.

**language model loss 관련**
해당 GPT 코드에서는 loss function으로 CrossEntropyLoss를 쓰는 것으로 확인했습니다. 아시다시피 크로스엔트로피는 negative log-likelihood와 밀접한 관련이 있는데요. `P(꿈)`, `P(보다|꿈)`, `P(해몽|보다, 꿈)` 각각을 높이는 것은 (1) `P(꿈) * P(보다|꿈) * P(해봉|보다, 꿈)`을 높인다 (2) `logP(꿈) + logP(보다|꿈) + logP(해봉|보다, 꿈)`을 높인다 (3) `lm_logits`와 `target` 간의 cross entropy를 낮춘다고 볼 수 있을 것 같습니다.
아래는 vocab_size가 100이고, sequence_length가 2일 때 language model loss를 최대한 단순화해서 테스트해본 결과입니다. lm_logits의 차원수는 `[batch_size, vocab_size, sequence_length]`, target의 차원수는 `[batch_size, sequence_length]`입니다.

```python
import torch
loss = torch.nn.CrossEntropyLoss()
logit = torch.randn(1, 100, 2, requires_grad=True)
target = torch.empty(1, 2, dtype=torch.long).random_(100)
output_total = loss(logit, target) # tensor(4.5326, grad_fn=<NllLoss2DBackward>)
output1 = loss(logit[:, :, :1], target[:, :1]) # tensor(5.4817, grad_fn=<NllLoss2DBackward>)
output2 = loss(logit[:, :, 1:], target[:, 1:]) # tensor(3.5836, grad_fn=<NllLoss2DBackward>)
```

수행 결과를 보면 `output_total`은 `output1`과 `output2`의 평균임을 알 수 있습니다. 다시 말해 개별 target의 
negative log-likelihood를 각각 낮추는 것과 전체 시퀀스의 negative log-likelihood를 낮추는 것이 같은 의미라는 생각이 듭니다. 이에 대해서도 의견 여쭙고 싶습니다. 부족한 글 읽어주셔서 감사합니다.

**Comment by graykode** [comment]
@ratsgo 안녕하세요! 제 부족한 글에 상세하게 답변을 달아주셔서 감사합니다 :)
**self-attention 관련**
말씀하신대로 `P(보다|꿈) + P(해몽|보다,꿈) + ...` 이 맞습니다. 다만, 이를 구현하기 위해서는 Self-Attention에서 Masking으로 구현하는 것이 아닌 (Al-Rfou at el, 2018, arXiv 1808.04444)와 같은 방법으로 구현한다고 생각합니다.
![image](https://user-images.githubusercontent.com/10525011/66735470-64cfdc00-eea1-11e9-89d5-6099429723bd.png)

**language model loss 관련**
이에 대해서는 전적으로 동의합니다!

항상 감사드립니다. 👍

**Comment by ratsgo** [comment]
안녕하세요, @graykode 님! 코멘트 감사드립니다. **self-attention 관련** 코멘트에 대해 제 생각을 말씀드립니다. 어디까지나 제 생각이니 잘못된 게 있거나 첨언하실 게 있으시면 언제든 편히 말씀해주세요.

예시로 들어주신 논문은 다음 논문으로 알고 있습니다.

- Al-Rfou, Rami, et al. "Character-level language modeling with deeper self-attention." Proceedings of the AAAI Conference on Artificial Intelligence. Vol. 33. 2019.

예시로 그려주신 그림의 회색 화살표들은 논문에서 `causal attention mask`로 설명한 것으로 아는데요. 논문의 설명은 다음과 같습니다.

> Figure 1 shows our initial model with the causal attention mask limiting information flow from left to right. Each character prediction is conditioned only on the characters that appered earlier.

해당 논문에 이밖에 더 자세한 설명이 없어서 정확히는 모르겠지만, 해당 문구만 봐서는 **어텐션 마스킹**으로 Language Model을 만들고 있는 것으로 보이는데요. @graykode 생각은 어떠신지 여쭙고 싶습니다.

**Comment by graykode** [comment]
@ratsgo 안녕하세요! 먼저 제 부족한 글에 좋은 답변 남겨주셔서 감사드립니다 :)
처음에는 @ratsgo 님의 책에서 i==j에서 Attention을 하지 않은 점이 의문이였는데, 제가 @ratsgo 님의 답변을 꼼꼼하게 읽지 않고 구현 코드에만 맹신했던 점이 문제였다고 생각합니다 ㅠㅠ. 제가 참고 했던 구현 코드도 i==j일때 어텐션을 하는데, 이도 <start>, <end>와 같은 토큰이 들어가기 때문이라고 생각됩니다. 

더불어 [제가 참고 했던 해당 구현 코드](https://github.com/tingkai-zhang/openai-gpt-pytorch)에서는 `Al-Rfou, Rami, et al. "Character-level language modeling with deeper self-attention." Proceedings of the AAAI Conference on Artificial Intelligence. Vol. 33. 2019.` 논문의 Figure1의 (b)처럼 {t_0:t_{n-1}} -> {t_1:t_n}와 같이 Multiple Positions을 사용하는데 이는 어텐션 마스킹과 번외의 문제라고 생각됩니다.

좋은 답변을 통해 한 번더 깊게 생각해볼 수 있게 해주신점 감사드립니다. 또한 다른 분들이 이슈를 보고 쉽게 이해할 수 있도록 Self-Attention Masking에 대한 그림도 남겨봅니다 항상 좋은 글 감사드립니다

<img src="https://i.imgur.com/NWmJLFm.png" height="200px"/>
<img src="https://i.imgur.com/tNOGwST.png" height="200px"/>
<img src="https://i.imgur.com/fbyQanr.png" height="200px"/>
<img src="https://i.imgur.com/nthWoiB.png" height="200px"/>


> 안녕하세요, graykode님! 책을 정독해주시고 의견 남겨주셔서 진심으로 감사드립니다. @graykode 님 같은 열혈 독자 분들께 누가 되지 않도록 책을 열심히 썼는데 역시 부족한 부분이 많아서 부끄러운 마음뿐입니다.
> 
> P222와 P230에 관련해서는 @graykode 님 의견이 옳다고 생각합니다. 2판을 다음과 같이 수정해 두고 정오표에도 알리겠습니다. 곧 eBook도 출간 예정인데 eBook에는 바로 반영해두겠습니다.
> 
> * P222 : 개별 소프트맥스 값이 지나치게 작아지는 것을 방지 > 소프트맥스의 그래디언트가 작아지는 것을 방지
> * P230 : 전체 학습 데이터 토큰의 15%를 마스킹한다 > 학습 데이터 한 문장의 토큰의 15%를 마스킹한다
> 
> P228과 관련해서 제가 알기로 GPT는 `START`와 `END` 토큰을 쓰는 걸로 아는데요. 두 토큰을 고려하면 다음과 같이 어텐션 마스크를 구성할 수 있을 것 같습니다(0이 마스킹, Label은 이번에 맞출 단어).
> 
> <img alt="KakaoTalk_Photo_2019-09-28-10-15-24" width="300" src="https://user-images.githubusercontent.com/26211652/65809521-e99bd400-e1d8-11e9-8ccd-24bde3e7cfa4.png">
> 
> `START`, `END` 토큰을 생략하고 그린다면 다음과 같이 어텐션 마스크를 구성할 수 있을 것 같습니다(독자들의 이해를 수월하게 하기 위해 `START`, `END` 토큰을 생략한 아래 그림을 책에 넣었습니다).
> 
> <img alt="KakaoTalk_Photo_2019-09-28-10-15-10" width="270" src="https://user-images.githubusercontent.com/26211652/65809537-10f2a100-e1d9-11e9-9bde-8776c919516b.png">
> 
> 위 두 가지 경우 모두 모델이 맞춰야할 토큰 이후 정보(예컨대 `보다`를 맞춰야할 때 `꿈`만 참고, `해몽`을 맞춰야할 때 `꿈`, `보다`만 참고)를 가린다는 점에서 같다고 생각합니다.
> 
> 혹시 제가 잘못 알고 있거나 첨언하실 부분 있으시면 언제든지 말씀해주세요. 부족한 책인데 관심 가져주셔서 다시 한번 감사드린다고 말씀드리고 싶어요!

**Comment by ratsgo** [comment]
@graykode 님! 답변 진심으로 감사드립니다. 첨부해주신 그림 역시 이해가 아주 잘되는 것 같습니다. 이 다음번에 제가 다른 자료를 만들 때 참고하겠습니다. @graykode 님 의견을 적극 수용하여 2쇄에는 다음과 같이 수정을 하게 됐습니다. 덕분에 설명이 좀 더 명확해 졌다고 생각합니다. 진심으로 감사드립니다.


<img width="500" alt="스크린샷 2019-10-30 오전 11 30 19" src="https://user-images.githubusercontent.com/26211652/67824175-034a7700-fb09-11e9-994e-2becf1760ec4.png">
<img width="500" alt="스크린샷 2019-10-30 오전 11 30 32" src="https://user-images.githubusercontent.com/26211652/67824178-07769480-fb09-11e9-952d-9b56fbd95a53.png">
