### ISSUE TITLE
p.123 페이지 오류 제보

### ISSUE THREAD

**Issue by helloyjam** [ratsgo/embedding#24]
100번의 학습 기회 가운데 3~4번 정도는 학습에서 제외하게 된다는 문장에서

P(w_i)가 0.9684되었을때는 96번 정도를 학습에서 제외하는 표현이 맞는 것 같습니다.
3~4번에서 96~97번으로요~!

**Comment by ratsgo** [comment]
안녕하세요, @helloyjam 님! 말씀하신 부분이 정확합니다. Mikolov et al. (2013)에서도 다음과 같이 언급되어 있음을 확인했습니다.

<img width="600" alt="스크린샷 2019-10-02 오후 1 41 29" src="https://user-images.githubusercontent.com/26211652/66018567-a021f080-e51a-11e9-990a-dc493d289ee5.png">
<img width="600" alt="스크린샷 2019-10-02 오후 1 41 53" src="https://user-images.githubusercontent.com/26211652/66018569-a2844a80-e51a-11e9-9020-c02c95d9da57.png">

제보주셔서 진심으로 감사드립니다. 정오표와 2쇄에 반영하겠습니다.
