### ISSUE TITLE
p. 68 오류 제보 입니다.

### ISSUE THREAD

**Issue by graykode** [ratsgo/embedding#25]
안녕하세요. 
페이지 68에 아래서 5번째 줄  - 표 2-4의`내 마음 속에 영원히 기억될 최고의 명작이다`의 빈도가 아니라. `그 아이는 또바기 인사를 잘한다`가 맞는 것 같습니다.

또한 p72에 형태(form)이므로 p73맨 앞 단어에도 형식보다 형태로 오는게 맞는것 같습니다

더불어 P225의 트랜스포머 설명에서 Pointwise 보다 Position-wise가 좀 더 올바르지 않을까? 생각합니다!!
감사합니다 :D

**Comment by graykode** [comment]
+) p149 반대로 Shazeer et al(2016)는 단어 i, j가 저 빈도 단어 인데 두 단어의 동시 등장 빈도가 [0이면] -> [0과 반대되는 어감이 와야할 것 같습니다.]

**Comment by ratsgo** [comment]
안녕하세요, @graykode 님! 이렇게 자세히 리뷰해주시니 정말 감사한 마음뿐입니다. 순서대로 말씀드리겠습니다. 제가 잘못 아는 게 있거나 첨언하실 게 있으시면 언제든지 말씀해주세요!

- 표 2-4와 그림 2-4가 넘버링이 같아서 혼동을 줄 염려가 있습니다만, 원래 의도는 다음과 같은 표 2-4에서 k만큼을 더해 Add-k 스무딩을 실시한다는 취지로 서술했습니다. 다시 말해 저는 해당 단락을 `Freq(내, 마음, 속에, 영원히, 기억될, 최고의, 명작이다)=k`로 쓴 셈입니다. 
그런데 `P(또바기|아이는)=0`이라면 '아이는' 이후에 '또바기'라는 단어가 말뭉치에 단 한번도 등장하지 않았다는 것이고, 이는 곧 `Freq(그, 아이는, 또바기, 인사를, 잘한다)=0`이므로 여기에 Add-k 스무딩을 실시한다면 `Freq(그, 아이는, 또바기, 인사를, 잘한다)=k`가 됩니다.
요컨대 책의 서술(`표2-4의 '내 마음 속에 영원히 기억될 최고의 명작이다'의 빈도는 k가 된다`), 의견 주신 내용(`그림 2-4의 '그 아이는 또바기 인사를 잘한다'의 빈도는 k가 된다`) 모두 맞다는 생각이 듭니다.

<img width="500" alt="스크린샷 2019-10-04 오후 5 32 45" src="https://user-images.githubusercontent.com/26211652/66193173-fd5da380-e6cc-11e9-9723-0b178987084d.png">

- 말씀 주신 부분에 100% 동의합니다. 다만 제가 참고한 학교문법(남기심&고영근, 표준국어문법론, 2009)에서는 form을 형식으로 쓰고 있으므로, 72페이지를 다음과 같이 고치겠습니다. 언어학자들이 제시하는 품사 분류 기준은 기능(function), 의미(meaning), 형태(form) 등 세 가지다. > 학교문법에 따르면 품사 분류 기준은 기능(function), 의미(meaning), 형식(form) 등 세 가지다.

- 오 정확한 지적입니다. `Position-wise`로 고치겠습니다. 세심한 코멘트 진심으로 감사드립니다.
