### ISSUE TITLE
nccl를 import 할수 없다고합니다.

### ISSUE THREAD

**Issue by indexxlim** [ratsgo/embedding#27]
안녕하세요
bert를 fine-tuning 해보려고 데이터 찾아 넣었는데 로그를 보니까
  1 Traceback (most recent call last):
  2   File "models/tune_utils.py", line 5, in <module>
  3     from tensorflow.contrib import nccl
  4 ImportError: cannot import name nccl
라고 떠서 nccl을 찾아보니까 멀티 gpu를 위한 라이브러리 같더라구요
근데 이 에러를 해결 못했는데 멀티 gpu설정을 해야 nccl을 사용할수 있나요?

**Comment by ratsgo** [comment]
도커 컨테이너에서 실행하신건가요?
환경 정보를 적어주시면 검토해보겠습니다.

**Comment by ratsgo** [comment]
혹시 도커 컨테이너가 아니고, 높은 버전의 텐서플로를 사용 중이시라면 아래처럼 해보시면 어떨까 싶습니다.
참고하셔요.

```python
import tensorflow as tf
if tf.VERSION.startswith('1.13'):
    from tensorflow.python.ops import nccl_ops as nccl
else:
    from tensorflow.contrib import nccl
```

그리고 `tune_utils.py`에서 멀티 지피유, nccl을 사용하는 모델은 XLNet뿐입니다.
따라서 BERT만 파인 튜닝하신다고 한다면 nccl 관련 에러가 나는 부분은 무시하시고 진행하셔도 됩니다.

**Comment by indexxlim** [comment]
도커를 사용하지 않아서 그랬나봅니다 감사합니다.
