### ISSUE TITLE
p.121에 대해

### ISSUE THREAD

**Issue by ohhara79** [ratsgo/embedding#28]
다시 말해 이 다음 학습 데이터를 만들 때는 "를"이라는 단어가 타깃단어(t)가 되고 "빨래"는 문맥 단어(c)가 된다.
라는 문구가 있는데 그림 4-9를 보면 "를"이 문맥 단어(c)이고 "빨래"가 타깃단어(t)로 보입니다.
버그인지 확인 부탁드립니다.

**Comment by ratsgo** [comment]
안녕하세요, @ohhara79 님. 이슈 남겨주셔서 감사드립니다. 그림 4-9의 경우 `빨래`가 타깃단어(t), `를`이 문맥단어(c)인 상황입니다.
이번 타깃 단어 계산이 끝나고 다음 타깃을 설정할 때는 오른쪽으로 한칸 옮깁니다. 따라서 이 다음에는 `를`이 타깃단어, `빨래`가 문맥단어가 됩니다. 본문에서는 다음과 같이 언급하였습니다.

- Skip-gram 모델은 전체 말뭉치를 **단어별로 슬라이딩해 가면서** 학습 데이터를 만든다. 다시 말해 **이 다음 학습데이터를 만들 때는 를이라는 단어가 타깃단어가 되고 빨래는 문맥단어가 된다**.
