### ISSUE TITLE
p.123 ~ p.125에 대해

### ISSUE THREAD

**Issue by ohhara79** [ratsgo/embedding#29]
p.123
둘의 크기는 어휘 집합 크기(|V|) X 임베딩 차원수(d)로 동일하다
라고 되어 있는데 틀린 표현은 아니지만 U는 |V| X d고 V는 d X |V|라고 명확하게 해 주는 것이 더 좋을 것 같습니다.

p.125
U+V행렬을 임베딩으로 쓸 수도 있다. 혹은 U, V를 이어 붙여 2d차원의 단어 임베딩으로 사용할 수도 있다.
라고 되어 있는데 V대신에 V^T를 쓰는 것이 더 적절할 것 같습니다.

**Comment by ratsgo** [comment]
@ohhara79 님, 이슈 남겨주셔서 감사합니다. 정오표와 2쇄에 반영하겠습니다.
