### ISSUE TITLE
3장 전처리 코드 실행시 에러 문의 드립니다.

### ISSUE THREAD

**Issue by SonHyeSeon** [ratsgo/embedding#30]
안녕하세요! 제공해주신 docker 컨테이너에서 p81의 python 코드와 p85의 자동 전처리 bash 코드 실행시 에러가 발생하여 문의드립니다.

output = open(out_f, 'w') 실행시 no such file or directory 에러가 발생하는데 혹시 빠뜨린 설정사항이 있어서 그런걸까요??

아직 미숙하여 개발 환경 설정이 쉽지 않네요ㅜ

**Comment by ratsgo** [comment]
@SonHyeSeon 님 안녕하세요. 부족한 책인데 관심 가져주셔서 감사드립니다.
해당 에러는 `/notebooks/embedding/data/processed` 디렉토리가 없을 때 납니다.
해당 디렉토리를 만든 뒤(다음 명령어 수행) 실행해보시면 문제가 없을 것 같습니다.

```bash
mkdir -p /notebooks/embedding/data/processed
```

`bash preprocess.sh dump-raw-wiki` 이 스크립트를 실행할 때 해당 디렉토리를 자동으로 생성하도록 코드를 고치겠습니다. 번거롭게 해드려 죄송합니다.

**Comment by SonHyeSeon** [comment]
알려주신 방법 덕분에 no such file or directory 에러는 해결되었습니다. 감사합니다!

추가로 코드 3-2의 tokenize는 코드 3-4의 tokenize를 의미하는 것인가요? 또, 코드 3-4의 WIKI_REMOVE_CHARS에 일본어가 있던데 이부분은 어떻게 입력을 해야 하는지 잘 모르겠습니다.

**Comment by ratsgo** [comment]
@SonHyeSeon 님! 순서대로 답변 드리겠습니다.

- 네 맞습니다.
- 코드 3-4는 다음 링크를 따라 가시면 원본을 보실 수 있습니다. 해당 코드 블록만 복사해서 붙여 넣으시면 됩니다.
https://github.com/ratsgo/embedding/blob/master/preprocess/dump.py

**Comment by keemyo** [comment]
안녕하세요 위와 비슷한 이슈 같은데요.
# bash preprocess.sh dump-raw-wiki

download ko-wikipedia...
--2021-11-29 07:18:22--  https://dumps.wikimedia.org/kowiki/latest/kowiki-latest-pages-articles.xml.bz2
Resolving dumps.wikimedia.org (dumps.wikimedia.org)... 208.80.154.7, 208.80.154.7, 2620:0:861:1:208:80:154:7
접속 dumps.wikimedia.org (dumps.wikimedia.org)|208.80.154.7|:443... 접속됨.

ERROR: cannot verify dumps.wikimedia.org's certificate, issued by ‘CN=R3,O=Let's Encrypt,C=US ’:
  Issued certificate has expired.
To connect to dumps.wikimedia.org insecurely, use `--no-check-certificate'.
root@ca425d8f0f2e:/notebooks/embedding#

preprocess.sh의 다른 모든 것들은 정상적으로 다운이 되는데 dump-raw-wiki 해당 건만 작동하지 않습니다 ㅠ

**Comment by ratsgo** [comment]
안녕하세요. 도서에서 안내한 도커 환경에서 수행했는데 이상이 있는걸까요?ㅠ

**Comment by 2003jack** [comment]
> 안녕하세요. 도서에서 안내한 도커 환경에서 수행했는데 이상이 있는걸까요?ㅠ 자세한 수행 환경을 알려주시면 감사하겠습니다.

안녕하세요, 저도 위에분과 똑같은 에러가 나네요, 이번에 처음으로 도커를 깔아서 실행시켜보아서 실수가 있을수도 있지만, 기본적으로는 책에서 하라는 데로 (윈도우 컴퓨터지만 AWS 사용하지 않고 일단은 cpu 버전으로 진행중입니다) 혹시 해결책이 있을까요. 그냥 뒤에 --no-check-certificate 를 추가해서 코드를 돌려도 똑같은 상황이 발생하네요.

감사합니다

**Comment by sujinkim23** [comment]
@keemyo 님, 아래 명령어 수행해 보시고 다시 bash script 수행해 보시면 됩니다.
$ echo "check_certificate = off" >> ~/.wgetrc
출처: https://elecs.tistory.com/364 [늦깎이 공대생의 좌충우돌 이야기]
