### ISSUE TITLE
docker에서 jupyter notebook 띄우는 방법 질문드립니다! (환경설정)

### ISSUE THREAD

**Issue by JangDaehyuk** [ratsgo/embedding#31]
안녕하세요 기창님! 

책에 있는 python 코드를 실행해보려고 합니다. 

#### notebooks/embedding 실행
docker run -it --rm ratsgo/embedding-cpu bash

#### 도커 안에서 주피터 노트북 실행 
jupyter notebook --ip 0.0.0.0 --allow-root

이후 나오는 token 값으로 로그인하려고 하는데요.
도커에서 주피터를 띄울 때는 url 창에다가 [ip주소:8888] 을 눌러서
주피터 로그인 창이 나오면 거기에 
토큰값을 넣어서 주피터로 접속하는 것으로 알고 있습니다. 

하지만 localhost:8888
접속 시에 자꾸 거부당하고 있는데요. 이 부분에 대한 답을 구글링하고 있지만
쉽게 해결이 안되서 질문 드려봅니다 ㅠㅠ (현재 운영체제는 우분투입니다)

우분투에서 docker 실행시 고래 그림이 나오면서 ip 주소가 나오지는 않아서 그냥 
원래 ip주소:8888 입력 하고 있습니다. 제 생각에는 ip 주소를 잘못입력했거나 방화벽 문제인거 같은데 경험상 아시는 해결책 있으면 부탁드리겠습니다 ㅠㅠ

**Comment by ratsgo** [comment]
안녕하세요 @JangDaehyuk 님!
안그래도 주피터 노트북 사용 문의가 있어서 제가 알아보고 있었는데요.
저도 아직까지 뚜렷한 해결책을 찾지 못했습니다.
찾는대로 방법을 이 이슈에 공유 내지는 도커 이미지에 반영해 두겠습니다.

혹시 해결 방법을 아는 다른 분이 계시다면 이 이슈에 공유해주시면 감사하겠습니다.

**Comment by 4seaday** [comment]
저도 찾아보다가 방금 해결한 것 같은데욥!
localhost:8888 이 아니라 docker container의 ip 값을 넣어주어야 합니다!

docker ps -a
: 현재 컨테이너들의 ID를 확인해줍니다. 

docker inspect 컨테이너ID
: json 형태로 컨테이너 정보를 반한해주는데 여기서, 
맨 마지막 "Netwroks" : "IPAddress" : 부분의  IP를 찾아주세요.

docker 실행 후,
jupyter notebook --allow-root --NotebookApp.token=''
: 주피터 노트북을 실행해줍니다.

그 다음 크롬창을 띄워서 아까 찾았던 "컨테이너IP:8888"로 접속해주면 됩니다.

**Comment by mwmw7** [comment]
> 안녕하세요 @JangDaehyuk 님!
> 안그래도 주피터 노트북 사용 문의가 있어서 제가 알아보고 있었는데요.
> 저도 아직까지 뚜렷한 해결책을 찾지 못했습니다.
> 찾는대로 방법을 이 이슈에 공유 내지는 도커 이미지에 반영해 두겠습니다.
> 
> 혹시 해결 방법을 아는 다른 분이 계시다면 이 이슈에 공유해주시면 감사하겠습니다.

저는 아래와같이 alias해서 사용하고있네요 
@JangDaehyuk  port 맵핑 옵션사용해 보세요
go_embedding='docker run -it --rm --gpus all -p 8888:8888 ratsgo/embedding-gpu bash'
![image](https://user-images.githubusercontent.com/1140031/72416454-0c6aec00-37ba-11ea-8c15-541ab0317d3a.png)

**Comment by jucho2725** [comment]
제가 사용한 방법을 그대로 공유해드립니다.

docker container run —name embedding —gpus all -it -p 8888:8888 -v "/home/jucho/data/":/notebooks/embedding/data/ ratsgo/embedding-gpu bash

혹시 모르시는 분들을 위해 질문과 관련 없는 것 까지 설명하겠습니다.
→ 도커 컨테이너를 실행시킨다. 이름은 embedding 이고 모든 gpu 를 사용할 것이다. 표준입력을 받는 터미널을 사용하도록 한다.
→ 호스트의 8888포트를 컨테이너의 8888포트와 연결할 것이다.
→ 호스트에 있는 /home/jucho/data/ 내 콘텐츠들을 컨테이너 /notebooks/embedding/data/ 에 넣을 것이다
→ 이미지는 ratsgo/embedding-gpu 도커 이미지파일을 사용할 것이다
→ 컨테이너를 만들면서 주는 명령어는 bash 이다

저도 말씀하신 것 처럼 도커 시작시 나오는 ip 주소가 없었습니다.(Linux Mint)
인터넷 설정에서 ip 주소를 확인 후 ip주소:8888 입력시 해결되었습니다. 

감사합니다

**Comment by seunghakbae** [comment]
저는 mwmw7님의 코멘트 보고 아래 방식으로 했습니다.

docker run -it --rm -p 8888:8888 ratsgo/embedding-cpu bash

jupyter notebook --allow-root

저렇게 입력하니 다음과 같이 나왔습니다. 

  http://(1197427cf359 or 127.0.0.1):8888/?token=~~~ 

여기서 처음 docker 를 시작할 때 나온 ip주소를 http://{ip주소}:8888/?token=~~~ 에 넣으니 jupyter notebook이 잘 실행되었습니다.

**Comment by HanNayeoniee** [comment]
seunghakbae 님의 코멘트를 보고

`docker run -it --rm --gpus all -p 8888:8888 --name nlp04 ratsgo/embedding-gpu bash` 명령어로 컨테이너를 띄운 후

`jupyter notebook --allow-root` 명령어를 입력해 docker를 처음 시작할 때 나온 ip주소를 브라우저에 넣었는데 jupyter notebook이 뜨지 않습니다. 

제가 빠뜨린 점이나 잘못 한 부분을 알려주시면 감사하겠습니다.

**Comment by jucho2725** [comment]
@HanNayeoniee 예전에 코멘트를 달아두었더니 계속 메일이 오네요.
1. docker 를 local machine 에서 켜신게 맞나요? 만약 서버에서 오픈하고 외부에서 사용하는 거라면 서버 포트의 포워딩이 필요합니다
2. 로컬에서 docker 를 시작했는데 열리지 않는 경우 sudo lsof -i -P -n 을 통해 아래와 같이 포트가 열려있는지 확인해봐주세요 
![image](https://user-images.githubusercontent.com/46298038/115651307-dd044100-a365-11eb-8faa-dd04f267b711.png)
3. 그래도 안되면 생각나는건 jupyter config 를 확인하는 것 밖에 생각이 안나는군요..

저도 100% 아는 건 아니라 해결이 될지 모르겠네요. 해결하셨다면 답변 남겨주세요 :)
