### ISSUE TITLE
P106 코드 3-26

### ISSUE THREAD

**Issue by jinsilk** [ratsgo/embedding#32]
안녕하세요. P106 코드 3-26 에 대해서 문의드립니다.
bash preprocess.sh make-bert-vocab

위 코드에서 preprocess.sh 에  make-bert-vocab 를 명령어로 가지는 코드가 없는것 같습니다.

**Comment by ratsgo** [comment]
안녕하세요, @jinsilk 님! 관심 가져주셔서 감사드립니다. 위의 커밋에서 확인할 수 있듯 preprocess.sh에 make-bert-vocab을 추가하였습니다. 해당 스크립트를 실행하면 (1) 전처리가 완료된 위키백과(processed_wiki_ko.txt)를 비롯한 말뭉치를 내려 받고, (2) sentencepiece 패키지를 활용해 BPE vocabulary를 구축합니다. vocab 구축시 I/O는 다음과 같습니다.

- input : `/notebooks/embedding/data/processed/processed_wiki_ko.txt`
- output : `/notebooks/embedding/data/processed/bert.vocab`

**Comment by ratsgo** [comment]
스크립트는 코드 3-26(다음 코드 블록과 동일)을 그대로 수행하면 됩니다.

```bash
git pull origin master
bash preprocess.sh make-bert-vocab
```
