### ISSUE TITLE
p.138에 대해

### ISSUE THREAD

**Issue by ohhara79** [ratsgo/embedding#33]
log k에서 k가 무엇인지 궁금합니다.

**Comment by lovit** [comment]
아래의 식 SPMI 에서의 k 는 임의의 양의 상수입니다. 하지만 [Levy & Goldberg(2014)](https://papers.nips.cc/paper/5477-neural-word-embedding-as-implicit-matrix-factorization) 에서 k 는 Word2Vec Skip gram 의 negative samples 의 개수와 동치임이 증명되었습니다. 

```
SPMI (A, B) = PMI(A, B) − log k
```

**Comment by ratsgo** [comment]
@lovit 님 말씀이 맞습니다. @ohhara79 님, @lovit 님 부족한 책에 관심 가져주셔서 진심으로 감사드립니다.
