### ISSUE TITLE
p181 오류 제보입니다.

### ISSUE THREAD

**Issue by toriving** [ratsgo/embedding#34]
안녕하세요. 책을 열심히 읽다가 잘못된점이 있는것 같아서 제보드립니다 :)
181페이지의 마지막 문단 "그림 5-3 왼쪽 리스트는 ~" 에서 왼쪽이 아니라, 오른쪽으로 변경해야 할 것 같습니다.
이와 마찬가지로 동일한 문단에서 "그림 5-3의 우측 그림은 실제 ~ "에서 우측을 좌측으로 변경해야 맞을 것 같습니다.

**Comment by ratsgo** [comment]
@toriving 님 코멘트 감사드립니다. 정오표와 2쇄에 반영하였습니다.
