### ISSUE TITLE
[공지] 2쇄 및 전자책 발간 일정 안내

### ISSUE THREAD

**Issue by ratsgo** [ratsgo/embedding#36]
안녕하세요! 독자 여러분의 성원에 힘입어 2쇄 및 전자책 발간 일정이 다음과 같이 확정되었습니다. 

- 종이책 2쇄 발간일 : 2019년 10월 31일
- 전자책 발간일 : 2019년 11월 29일

부족한 책인데 이만큼 성원해 주셔서 진심으로 감사드립니다. 어깨가 무거워집니다.
본 레파지토리 이슈, 메일 등 다양한 방식으로 여러분들이 오류, 개선 사항에 대한 피드백을 주셨는데요.

10월 28일까지 들어온 모든 내용에 대해서는 종이책 2쇄에 반영을 하였습니다.
이후 추가 오류나 개선 의견 등에 대해서는 전자책에 반영할 예정입니다.

다시 한번 머리 숙여 감사드립니다.

이기창 올림

**Comment by Huffon** [comment]
너무 감사히 잘 보고 있습니다. 
책을 교재로 스터디도 진행하고 있습니다 ㅎㅎ (https://github.com/nlp-kkmas/korean-embedding-study)
얼른 완독하고 감사 리뷰 올릴 수 있도록 하겠습니다 :)

**Comment by ratsgo** [comment]
@Huffon 님! 스터디까지 하시다니 부담감이 커지네요.
스터디 하시면서 궁금한 점이나 오류, 개선사항 있으시면 언제든 이슈 올려주세요.
진심으로 감사드립니다.

**Comment by Ronalmoo** [comment]
하루의 시작과 마무리를 이 책과 함께 하고 있습니다! ㅎㅎ
좋은 책 써주셔서 감사합니다
