### ISSUE TITLE
bert 시각화 문의

### ISSUE THREAD

**Issue by lthwea** [ratsgo/embedding#37]
안녕하세요

책에 있는 버트 시각화 코드를 실행하고 있는데 출력이 안되서요~
제가 뭔가 빠트리고 있는건지, 코드는 정상 작동하는지 궁금하네요~

![스크린샷 2019-11-05 오전 5 23 44](https://user-images.githubusercontent.com/6447619/68155214-96adfd00-ff8c-11e9-83ad-e088717bed31.png)

확인 좀 부탁드립니다~
감사합니다

**Comment by ratsgo** [comment]
안녕하세요, @lthwea 님! 기존 코드는 파이썬 콘솔에서 실행한다는 전제 하에 시각화 결과물을 `/notebooks/embedding/self-attention.png`에 저장하는 기능을 구현한 것입니다. 말씀하신 것처럼 주피터 노트북에서 시각화 결과물을 바로 확인하려면 plot을 `export_png(plot, filename)` 대신 다음과 같이 처리해야 합니다.

```python
from bokeh.io import output_notebook, show
output_notebook()
show(plot)
```

그런데 일일이 이렇게 고치기에는 번거로우므로  `BERTEmbeddingEvaluator`를 선언할 때 `use_notebook=True`로 켜면 주피터 노트북 시각화가 가능하도록 코드를 개선하였습니다. 아래처럼  `BERTEmbeddingEvaluator`를 선언하면 됩니다.

```python
from model.sent_eval import BERTEmbeddingEvaluator
model = BERTEmbeddingEvaluator(model_fname, bertconfig_fname, vocab_fname, max_seq_length, dimension, num_labels, use_notebook=True)
```

이후 시각화 관련 함수들을 실행하면 정상 작동할거라 생각합니다. 감사합니다.
