### ISSUE TITLE
텍스트마이닝을 공부하는 학생입니다. 194쪽 제일위에 LSA -> LDA 인가요?

### ISSUE THREAD

**Issue by rok805** [ratsgo/embedding#38]
오타인지 아니면 저의 무지인지 잘 모르겠습니다.

**Comment by ratsgo** [comment]
@rok805 님 안녕하세요! 말씀하신 것처럼 오타가 맞습니다. 정오표와 전자책에 반영해 두겠습니다. 부족한 책인데 관심 가져주셔서 감사합니다.
