### ISSUE TITLE
P.211 ELMo Figure 질문입니다.

### ISSUE THREAD

**Issue by kkizu** [ratsgo/embedding#41]
역방향 LSTM에서 각 LSTM Cell에서 예측하는 값들이 잘못된것 같습니다.
우측부터 첫번쨰라고 할때 첫번째 LSTM Cell에서는 '먹자'의 전 단어인 '밥'을 예측해야 한다고생각합니다.
그림에서는 '먹자'의 다음 단어인 '<EOS>'를 예측하게 되어있는데, 이 경우 두번째 LSTM cell에서는 이미 그 전 LSTM Cell에서 '먹자'를 봤으므로 '먹자'라는 단어를 예측하는게 쉬워질 것 같습니다.
또한 gamma^task에 대한 추가 설명이 필요할 것 같습니다. 내용만으로는 이해가 되지 않습니다.

**Comment by ratsgo** [comment]
@kkizu 님 안녕하세요. 그림 5-18을 2쇄에 다음과 같이 반영하였습니다. 정오표에 공지했어야 했는데 제가 깜빡하고 있었네요.

<img width="800" alt="스크린샷 2019-11-24 오후 7 25 08" src="https://user-images.githubusercontent.com/26211652/69493271-40c7d780-0ef0-11ea-8413-2a72f4608c0d.png">

gamma^task와 관련해 논문 저자는 다음과 같이 언급하고 있습니다. ELMo 벡터(BiLM의 weighted sum vector)의 크기를 스케일하는 역할을 하며, task당 하나의 값을 가지는 걸로 이해했습니다. gamma^task는 파인튜닝 과정에서 학습되는 파라메터입니다. 문서 분류, 감성 분석, 개체명 인식 등 task마다 요구받는 임베딩 공간이 다르기 때문에 이를 조정해주는 역할을 수행하는 듯합니다. BiLM의 맨 마지막 레이어로만 ELMo 벡터를 만드는 경우(last-only case) gamma^task가 없으면 성능 하락이 꽤 크다고 합니다.

<img width="500" alt="스크린샷 2019-11-24 오후 7 19 00" src="https://user-images.githubusercontent.com/26211652/69493280-61902d00-0ef0-11ea-98e8-eed570eef2cd.png">

<img width="500" alt="스크린샷 2019-11-24 오후 7 21 40" src="https://user-images.githubusercontent.com/26211652/69493283-694fd180-0ef0-11ea-96a2-6752d2982fc3.png">
