### ISSUE TITLE
126쪽 코드 질문

### ISSUE THREAD

**Issue by TransAmRaiser** [ratsgo/embedding#42]
1. 코드 4-4 오류

코드 4-4를 실행하면 조금 뒤에 '죽었음'이라는 메시지가 출력되고 제대로 된 결과물이 얻어지지 않습니다. 
우분투 16.04, MacOS Catalina, Windows 10 환경에서 모두 해 보았으나 전부 제대로 실행되지 않았습니다.

물론 이전 과정인 전 처리, 형태소 분석을 모두 수행한 이후에 실행을 한 것입니다.
그런데도 자꾸 코드 4-4가 제대로 실행되지 않아서, '죽었음'을 키워드로 구글링을 해 보니 메모리 부족 문제라는 글들이 보이더군요.
딱히 설정을 안 건드려도 실행이 되도록 튜토리얼을 구성하셨으리라고 생각은 됩니다만,
혹시나 하여 도커 설정에서 CPUs:4, Memory: 14848 MB, Swap: 2048MB로 자원을 대폭 늘려 봤습니다. (Windows 10 환경)
그러나 '죽었음' 메시지가 출력되는 시간이 훨씬 늦어질 뿐 여전히 실행되지 않습니다.
무슨 문제인지, 어떻게 해결해야 되는지 궁금합니다.

2. 코드 4-1의 데이터 관련

코드 4-1이 '형태소 분석 완료된' 데이터를 다운로드하는 것이라고 되어 있습니다만, 다운받은 파일을 에디터로 열어 보면 형태소 단위로 토큰화만 되어 있습니다.
형태소 분석을 했다고 하면 형태소 뒤에 태그까지 있어야 되는 거로 이해되는데, 원래 워드 벡터를 만들 때 이런 식으로 태그 없이 토큰화만 해서 만드는 게 일반적인지요?
그러면 동철자인 형태소들끼리 구별이 안 돼서 좀 이상해지는 게 아닌가 싶어서 여쭙습니다.

**Comment by ratsgo** [comment]
@TransAmRaiser 님 부족한 책인데 관심 가져 주셔서 감사드립니다. 원래는 1, 2번 질문 모두 해결한 상태에서 답을 드리려고 했는데요. 시간이 너무 지체되는 것 같아서 먼저 2번 질문과 관련해 제가 아는대로 답을 드리겠습니다.

- **형태소 분석을 했다고 하면 형태소 뒤에 태그까지 있어야 되는 것 아닌가?**
`문장(string)`을 `토큰 시퀀스(list of string)` 형태로 바꾸는 과정을 `토크나이즈(tokenize)`라고 합니다. 각 토큰에 `품사(Part Of Speech, 동사, 형용사, 명사 따위)` 정보를 부착하는 과정을 `품사 판별(POS tagging)`이라고 합니다. 우리 책에는 `토큰(token)`, `형태소(morpheme)`, `서브워드(subword)` 등을 별도로 구분하고 있지 않고 있습니다(자세한 내용은 서론 마지막 장 참조). 이에 토크나이즈를 '형태소 분석'이라고 표현하고 있습니다.
- **워드 벡터를 만들 때 태그 없이 토큰화만 해서 만드는 게 일반적인지?**
꼭 그렇지는 않습니다. 말씀하신 것처럼 품사 정보를 함께 써서 같은 소리가 나는 단어를 품사별로 얼마든지 각각 임베딩할 수 있습니다(예: 이/조사, 이/관사, 이/명사 등). 다만 우리 책 실습에서는 토큰화로만 임베딩을 수행했습니다. 이렇게 하면 말씀하신 것처럼 동철자인 형태소끼리는 구별이 되지 않습니다. 이는 단어 수준 임베딩의 한계이기도 합니다. 물론 ELMo, BERT 같은 문장 수준 임베딩 기법에서는 품사 정보 없이도 동음이의어를 분간할 수 있습니다.

1번 질문과 관련한 해당 코드는 gensim의 word2vec 학습 코드로 알고 있는데요. 제가 다시 테스트를 해보고 있습니다. 정리되는대로 말씀드리겠습니다. 감사합니다.

**Comment by ratsgo** [comment]
@TransAmRaiser 님 늦어서 죄송합니다. 1번 질문과 관련해서는 학습데이터에 속한 일부 문서 길이(토큰 수 기준)가 너무 길어서 발생하는 문제로 파악됐습니다. 우리 책에서 사용하는 gensim word2vec 패키지는 문서 단위로 메모리에 올려서 임베딩을 학습하는데 이 문서 길이가 지나치게 길면(통계량 확인 결과 10만569개 토큰이 있는 문서가 가장 긴 문서로 나타났습니다) 메모리 문제로 죽는 문제가 발생하는 듯합니다. 저 같은 경우에는 책을 쓸 때 RAM이 충분한 곳에서 작업하느라 이 문제를 미처 발견하지 못했습니다.
이에 코드를 수정해 word2vec 학습에 쓰는 문서 최대 토큰 길이(`max_num_tokens_per_doc`)를 정할 수 있도록 옵션을 추가하였습니다. 이보다 긴 문서는 이 길이로 맞춰서 학습데이터를 만듭니다. 만약 책에서처럼 `max_num_tokens_per_doc`을 별도로 지정하지 않는다면 `max_num_tokens_per_doc`는 말뭉치 내 가장 긴 문서의 길이가 됩니다. 아래처럼 수행하면 됩니다.

```bash
python models/word_utils.py --method train_word2vec  --input_path data/tokenized/corpus_mecab.txt  --output_path data/word-embeddings/word2vec/word2vec  --max_num_tokens_per_doc 100000
```

**Comment by TransAmRaiser** [comment]
답변 감사드립니다. 다른 문제가 있으면 다시 말씀드리겠습니다.
