### ISSUE TITLE
page 98. 표 3-3 오타

### ISSUE THREAD

**Issue by hccho2** [ratsgo/embedding#46]
page: 98
Kkma형태소 분석 결과와 Mecb 분석 결과에 오타가 있습니다.

Kkma에 '에/JKM'  ---> '들어가/VV'
Mecab에 '가/JKS'가 2번 나옵니다. '방'으로 수정 필요.

===================
page 168
코드 4-46에 정의된  ----> 코드 4-47에 정의된

===================
page 170
코드 4-51에서
--embedding_corpus_path 로 'corpus_mecab.txt'를 넣어주고 있는데,
corpus_mecab.txt라는 파일은 없는 것 같습니다. 흐름상으로는 네이버 영화 리뷰 말뭉치가 들어가야 되니, 'ratings_mecab.txt'이 되어야 하지 않을까요?

===================
page 184
w_0, w_1, ..., w_{T-1}이기 때문에,
수식 5-1에서 \Sigma_{t=k}^{T-k}  ===> \Sigma_{t=k}^{T-1} 
이렇게 수정되어야 될 것 같습니다.

===================
page 187
코드 5-11에서
'Togged Document'  ---> 'TaggedDocument'

from gensim.models.doc2vec import Togged Document
==> 
from gensim.models.doc2vec import TaggedDocument

**Comment by ratsgo** [comment]
@hccho2 님 부족한 책인데 자세히 읽어주셔서 감사드립니다. 순서대로 말씀드리겠습니다.

- **page: 98/ Kkma형태소 분석 결과와 Mecb 분석 결과에 오타가 있습니다.**
저도 오타를 나중에야 발견하고 깜짝 놀랐습니다. 2쇄에 다음과 같이 반영했습니다. 정오표에도 공지해 두겠습니다.

<img width="500" alt="스크린샷 2019-11-28 오전 11 58 10" src="https://user-images.githubusercontent.com/26211652/69773511-6bf34500-11d6-11ea-9855-c7d4561ab97e.png">

**Comment by ratsgo** [comment]
- **page 168/ 코드 4-46에 정의된 ----> 코드 4-47에 정의된**
정확한 지적입니다. 정오표와 전자책에 반영해 두겠습니다.

**Comment by hccho2** [comment]
> @hccho2 님 부족한 책인데 자세히 읽어주셔서 감사드립니다. 순서대로 말씀드리겠습니다.
> 
> * **page: 98/ Kkma형태소 분석 결과와 Mecb 분석 결과에 오타가 있습니다.**
>   저도 오타를 나중에야 발견하고 깜짝 놀랐습니다. 2쇄에 다음과 같이 반영했습니다. 정오표에도 공지해 두겠습니다.
> 
> <img alt="스크린샷 2019-11-28 오전 11 58 10" width="500" src="https://user-images.githubusercontent.com/26211652/69773511-6bf34500-11d6-11ea-9855-c7d4561ab97e.png">

**Comment by ratsgo** [comment]
- **page 170 코드 4-51에서 'ratings_mecab.txt'이 되어야 하지 않을까요?**
코드 4-2, 코드 4-4, 코드 4-11 등에 Mecab으로 형태소 분석한 위키백과, 네이버 리뷰, KorQuAD를 합치는 과정을 안내했었는데요. 이게 너무 멀리 떨어져 있다보니 혼동을 줄 염려가 있을 것 같다는 생각이 들었습니다. 170페이지에 해당 내용을 추가로 명시하겠습니다.

**Comment by hccho2** [comment]
이 부분은 제가 잘 못 이해했네요^^

**Comment by ratsgo** [comment]
- **page 184 w_0, w_1, ..., w_{T-1}이기 때문에, 수식 5-1에서 \Sigma_{t=k}^{T-k} ===> \Sigma_{t=k}^{T-1}
이렇게 수정되어야 될 것 같습니다.**
네 맞습니다. 전자책과 정오표에 공지하겠습니다. 꼼꼼하게 읽어주셔서 진심으로 감사드립니다.

**Comment by ratsgo** [comment]
- **page 187 코드 5-11에서 'Togged Document' ---> 'TaggedDocument'**
헉! 오타 제보 감사드립니다.
