### ISSUE TITLE
unzip error

### ISSUE THREAD

**Issue by embed-Rayn** [ratsgo/embedding#47]
![image](https://user-images.githubusercontent.com/57181674/69802898-f9a65300-121d-11ea-9aea-f3a810aa8200.png)
코드 4-1을 실행 시 이렇게 나오는데 몇몇 gdrive 파일이 손상되지 않았나 의심이 갑니다.
파일을 다운로드 후 unzip 시  zipfile을 찾을 수 없다고 나오고 이 외에도 몇 파일은 이런 에러가 발생했는데 제가 실수를 하고 있는지 알려주세요

**Comment by ratsgo** [comment]
@embed-Rayn 님 안녕하세요. 부족한 책에 관심 가져주셔서 감사드립니다. 제가 우분투와 MacOS 두 환경에서 각각 `ratsgo/embedding-gpu`, `ratsgo/embedding-cpu` 도커 이미지에서 체크한 결과 모두 이상이 없음을 확인하였습니다. 혹시 코드 업데이트를 하셨는지요. 다음처럼 한번 실행해 보시고 이상이 있으면 자세한 실행환경을 공유 부탁드리겠습니다.

```bash
git pull origin master
bash preprocess.sh dump-tokenized
```

**Comment by embed-Rayn** [comment]
bash preprocess.sh dump-word-embeddings
bash preprocess.sh dump-sentence-embeddings
bash preprocess.sh dump-tokenized
bash preprocess.sh dump-processed
등 몇개의 명령에서 unzip에러가 발생했고 bash 파일의 rm 명령어를 지우고 다운 받은 .zip파일을 들어가보니 아래와 같은 html 문서가 들어 있었습니다.
<!DOCTYPE html><html><head><title>Google Drive - Virus scan warning</title><meta http-equiv="content-type" content="text/html; charset=utf-8"/><link href=&#47;static&#47;doclist&#47;client&#47;css&#47;3309678740&#45;untrustedcontent.css rel="stylesheet"><link rel="icon" href="https://ssl.gstatic.com/docs/doclist/images/infinite_arrow_favicon_4.ico"/><style nonce="8fa8blZY3Hn0FgOndJy2hQ">#gbar,#guser{font-size:13px;padding-top:0px !important;}#gbar{height:22px}#guser{padding-bottom:7px !important;text-align:right}.gbh,.gbd{border-top:1px solid #c9d7f1;font-size:1px}.gbh{height:0;position:absolute;top:24px;width:100%}@media all{.gb1{height:22px;margin-right:.5em;vertical-align:top}#gbar{float:left}}a.gb1,a.gb4{text-decoration:underline !important}a.gb1,a.gb4{color:#00c !important}.gbi .gb4{color:#dd8e27 !important}.gbf .gb4{color:#900 !important}
</style><script nonce="8fa8blZY3Hn0FgOndJy2hQ"></script></head><body><div id=gbar><nobr><a target=_blank class=gb1 href="https://www.google.co.kr/webhp?tab=ow">Search</a> <a target=_blank class=gb1 href="http://www.google.co.kr/imghp?hl=en&tab=oi">Images</a> <a target=_blank class=gb1 href="https://maps.google.co.kr/maps?hl=en&tab=ol">Maps</a> <a target=_blank class=gb1 href="https://play.google.com/?hl=en&tab=o8">Play</a> <a target=_blank class=gb1 href="https://www.youtube.com/?gl=KR&tab=o1">YouTube</a> <a target=_blank class=gb1 href="https://mail.google.com/mail/?tab=om">Gmail</a> <b class=gb1>Drive</b> <a target=_blank class=gb1 href="https://www.google.com/calendar?tab=oc">Calendar</a> <a target=_blank class=gb1 style="text-decoration:none" href="https://www.google.co.kr/intl/en/about/products?tab=oh"><u>More</u> &raquo;</a></nobr></div><div id=guser width=100%><nobr><span id=gbn class=gbi></span><span id=gbf class=gbf></span><span id=gbe></span><a target="_self" href="/settings?hl=en_US" class=gb4>Settings</a> | <a target=_blank  href="//support.google.com/drive/?p=web_home&hl=en_US" class=gb4>Help</a> | <a target=_top id=gb_70 href="https://accounts.google.com/ServiceLogin?hl=en&passive=true&continue=https://docs.google.com/uc%3Fexport%3Ddownload%26confirm%3Dh%26id%3D1Ybp_DmzNEpsBrUKZ1-NoPDzCMO39f-fx&service=writely" class=gb4>Sign in</a></nobr></div><div class=gbh style=left:0></div><div class=gbh style=right:0></div><div class="uc-main"><div id="uc-dl-icon" class="image-container"><div class="drive-sprite-aux-download-file"></div></div><div id="uc-text"><p class="uc-warning-caption">Google Drive can't scan this file for viruses.</p><p class="uc-warning-subcaption"><span class="uc-name-size"><a href="https://docs.google.com/open?id=1Ybp_DmzNEpsBrUKZ1-NoPDzCMO39f-fx">tokenized.zip</a> (832M)</span> is too large for Google to scan for viruses. Would you still like to download this file?</p><a id="uc-download-link" class="goog-inline-block jfk-button jfk-button-action" href="/uc?export=download&amp;confirm=X7py&amp;id=1Ybp_DmzNEpsBrUKZ1-NoPDzCMO39f-fx">Download anyway</a></div></div><div class="uc-footer"><hr class="uc-footer-divider">&copy; 2019 Google - <a class="goog-link" href="//support.google.com/drive/?p=web_home">Help</a> - <a class="goog-link" href="//support.google.com/drive/bin/answer.py?hl=en_US&amp;answer=2450387">Privacy & Terms</a></div></body></html>

파일이 커서 구글에서 바이러스 검사를 수행할 수 없다는 내용인데... 어찌 해결 할 방법 없을까요?
AWS로 했을 땐 잘 되었는데 회사 서버로 하니 이런 상황이 발생하네요.

**Comment by ratsgo** [comment]
@embed-Rayn 님 안녕하세요. 구글 드라이브에서 대용량 파일을 다운로드할 때 바이러스 검사를 회피하고 바로 다운로드 받는 코드를 클론 받아 사용해보시는 건 어떨까요? 수행 방법은 다음과 같습니다.

**설치**
```bash
git clone https://github.com/chentinghao/download_google_drive.git
pip install tqdm
```

**수행 예시**
```bash
cd download_google_drive
# python download_gdrive.py file_url_id save_file_path
python download_gdrive.py 1Few7-Mh3JypQN3rjnuXD8yAXrkxUwmjS processed_blog.txt
```

다음은 본 도서에서 제공하고 있는 리소스 파일들의 구글 드라이브 id와 파일 이름 리스트입니다. 참고가 되셨으면 좋겠습니다.

|종류|google drive id|file-name|
|---|---|---|
|ratsgo blog (raw)|1Few7-Mh3JypQN3rjnuXD8yAXrkxUwmjS|processed_blog.txt|
|processed corpus|1kUecR7xO7bsHFmUI6AExtY5u2XXlObOG|processed.zip
|tokenized corpus|1Ybp_DmzNEpsBrUKZ1-NoPDzCMO39f-fx|tokenized.zip|
|word embeddings|1FeGIbSz2E1A63JZP_XIxnGaSRt7AhXFf|word-embeddings.zip|
|sentence embeddings|1jL3Q5H1vwATewHrx0PJgJ8YoUCtEkaGW|sentence-embeddings.zip|
|ELMo|1go2JtVeYBOjkBCWJWk8inkSpVg7VfFVp|elmo.zip|
|BERT(1)|1DEpdPRJc-kjmeU_5pgMPzTOuH8qrwIzY|bert_config.json|
|BERT(2)|12cCImHAM97lXb427vCl_3MXOY7bxNlYe|bert_model.ckpt.data-00000-of-00001|
|BERT(3)|10jD8gN94Vr_5XMftheJB7n0IBm-pjdwd|bert_model.ckpt.index|
|BERT(4)|1pLNR2xL17HCLD3GmWCLls7a9xhhDIdw2|bert_model.ckpt.meta|
|BERT(5)|1LkyTFPeoTvWoO5XP0bDi3Af53XPCLE59|vocab.txt|

일일이 치기 번거로우시면 `preprocess.sh` 스크립트 내에 gdrive_download 부분을 `python download_google_drive/download_gdrive.py`로 바꿔서 써보는 것도 좋을 것 같습니다.
