### ISSUE TITLE
p.184 수식 5-1 문의

### ISSUE THREAD

**Issue by embed-Rayn** [ratsgo/embedding#48]
![image](https://user-images.githubusercontent.com/57181674/69804387-cbc30d80-1221-11ea-96a6-a7bb5d0004ba.png)
이렇게 이해가 됐는데 책이 맞나요?

**Comment by black7375** [comment]
제 생각에는 책이 맞는 듯 합니다.

* `t`: 전체 문장을 이루는 단어토큰 갯수
* `k`: 슬라이싱할 단어 갯수 (n-gram에서 `n` 역할)
같아요.

**Comment by hccho2** [comment]
w_0, w_1, ..., w_{T-1}이기 때문에,
수식 5-1에서 \Sigma_{t=k}^{T-k} ===> \Sigma_{t=k}^{T-1}

제 생각에는 이렇게 되어야 할 것 같습니다만...

**Comment by embed-Rayn** [comment]
다시보니 @hccho2 님이 맞는 것 같아요. 책의 예제인 the cat sat on the man을 보면
k = 3, T = 6이고 
log P(w_3 | w_2, w_1, w_0)+log P(w_4 | w_3, w_2, w_1)+log P(w_5 | w_4, w_3, w_2)
가 되려면 Sigma_{t=k}^{T-1}이 맞겠네요
> w_0, w_1, ..., w_{T-1}이기 때문에,
> 수식 5-1에서 \Sigma_{t=k}^{T-k} ===> \Sigma_{t=k}^{T-1}
> 
> 제 생각에는 이렇게 되어야 할 것 같습니다만...

**Comment by black7375** [comment]
논문 있네요
https://cs.stanford.edu/~quocle/paragraph_vector.pdf

**Comment by hccho2** [comment]
논문에서는 중심단어의 앞 k개, 뒤 k개를 모델링하는 수식이고, 책에서는 앞 k개를 사용하기 때문에 조금 차이가 있습니다.

**Comment by black7375** [comment]
@hccho2 
넵. 저도 그렇게 이해했습니다.

**Comment by ratsgo** [comment]
@embed-Rayn @hccho2 @black7375 님! 제가 잠시 자리를 비우는 사이에 활발한 토론을 해주셨네요^^; 뒤늦게 말씀드려서 죄송하지만 결론부터 말씀드리면 @hccho2 님 말씀이 맞습니다. @hccho2 님께서 다른 이슈에 이 내용을 이미 지적해주셨는데요. [해당 이슈](https://github.com/ratsgo/embedding/issues/46#issuecomment-561622471)에도 동일한 답변을 달았습니다. 부족한 책인데 관심 가져주셔서 진심으로 감사드립니다.
