### ISSUE TITLE
page 216 clip에 관하여

### ISSUE THREAD

**Issue by hccho2** [ratsgo/embedding#49]
page 216 ELMo 모델의 
lstm_cell = tf.nn.rnn_cell.LSTMCell(lstm_dim, num_proj=projection_dim,	cell_clip=cell_clip, proj_clip=proj_clip)

여기서, cell_clip,proj_clip에 대하여, gradient를 clip한다고 책에서 설명하고 있습니다.

 tf.nn.rnn_cell.LSTMCell API의 설명이나, 구현을 찾아보면, gradient를 clip하는 것이 아니고, 값 자체를 clip한다고 되어 있습니다.

https://www.tensorflow.org/api_docs/python/tf/compat/v1/nn/rnn_cell/LSTMCell

확인 부탁드립니다.

**Comment by ratsgo** [comment]
@hccho2 님 말씀이 맞습니다. 다음처럼 API 설명과 코드 구현 모두 값 자체를 clip하는 것으로 확인했습니다. 전자책과 정오표에 반영하겠습니다. 꼼꼼하게 봐주셔서 진심으로 감사드립니다.

<img width="500" alt="스크린샷 2019-12-04 오후 9 51 13" src="https://user-images.githubusercontent.com/26211652/70144046-720a8980-16e0-11ea-8564-323a888677be.png">

<img width="500" alt="스크린샷 2019-12-04 오후 9 52 57" src="https://user-images.githubusercontent.com/26211652/70144059-7767d400-16e0-11ea-9502-607978fa5254.png">
