### ISSUE TITLE
212page 오탈자

### ISSUE THREAD

**Issue by hotorch** [ratsgo/embedding#50]
212 페이지 맨 밑에 문구에서

k번째 토큰의 j번째 레이어의 양방향, 역방향 LSTM 히든 벡터를 이어 ~~~ 

여기서 양방향, 역방향이 아니고 순방향, 역방향으로 수정하는 것이 맞는것 같습니다!!!!!!!

**Comment by ratsgo** [comment]
@hotorch 님 바로 잡아주셔서 감사드립니다. 전자책과 정오표에 반영하겠습니다.
