### ISSUE TITLE
3, 5, 6장 중 추가 설명 요청드립니다.

### ISSUE THREAD

**Issue by SonHyeSeon** [ratsgo/embedding#52]
### 5장

- [x] 1. **p207**, "_**ELMo의 original 모델에서는 **코드 5-27처럼** 컨볼루션 연산을 시행한다**_" 의 표현이 매끄럽지 못한 것 같습니다 코드 5-27에서는 ELMo original 모델에서 사용하는 필터 설정을 나타내고 있으므로 "_**ELMo의 original 모델에서는 **코드 5-27의 필터들을 사용하여** 컨볼루션 연산을 시행한다**_" 이런식으로 표현하면 좀 더 매끄럽지 않을까 생각합니다.

> ELMo의 original 모델에서는 **코드 5-27처럼** 컨볼루션 연산을 시행한다
> ELMo의 original 모델에서는 **코드 5-27의 필터들을 사용하여** 컨볼루션 연산을 시행한다
#
- [x] 2. **p207**, "_**코드 5-27에서는 컨볼루션 필터를 일곱 종류를 쓰고 있다**._" 이 부분이 7종류를 모두 사용하는 것인지 7종류 중 선택하여 사용하는 것인지 의미가 모호한 것 같습니다. p208 부분을 보면 ELMo 모델의 경우 7종류를 모두 사용한다는 것으로 이해할 수 있는데 p207 부분의 표현에 그 내용을 추가해주시면 더욱 매끄럽게 이해될 것 같습니다.
> 코드 5-27에서는 컨볼루션 필터를 일곱 종류를 쓰고 있다.
> 코드 5-27에서는 컨볼루션 필터를 일곱 종류를 **모두** 쓰고 있다.
#
- [x] 3. **p210**, 수식2 하이웨이 네트워크 표기 오타
> C(x,W_**c**)
> C(x,W_**C**)
#
- [x] 4. **p212**, **프리트레인 단계**와 **예측 단계**의 구분이 프리트레인 단계에서도 예측 역할을 하는 손실 레이어가 있기 때문에 모호한 것 같습니다. 예측 단계를 **파인 튜닝 단계**등으로 표현하면 좀 더 이해가 쉬울 것 같습니다!

*****

### 6장
- [x] 5. **p246**, 파일명 오타
> 한편 6장에서 언급하는 코드의 대부분은 **tuning_utils.py**에 정의돼 있다.
> 한편 6장에서 언급하는 코드의 대부분은 **tune_utils.py**에 정의돼 있다.
#
- [x] 6. **p249**, 코드 6-3 **if is_training:** 삭제
tune_utils.py를 확인해보면 log를 출력 하는 부분인 것 같아 삭제되어도 될 것 같습니다.
```{.python}
num_batches_per_eppoch = int((data_size - 1) / self.batch_size) + 1
if is_training:
for epoch in range(num_epochs) : 
```
```{.python}
num_batches_per_eppoch = int((data_size - 1) / self.batch_size) + 1
for epoch in range(num_epochs) : 
```
#
- [ ] 7. **p273**, **BERT의 파인 튜닝에서 BERT 모델에 문장을 입력해 스페셜 토큰 [CLS]에 해당하는 벡터를 추출한다.** 이 부분이 잘 이해가 되지 않습니다. 왜 전체 문장 벡터를 추출하지 않고 [CLS]벡터로만 파인 튜닝을 진행하는지, 그리고 P274의 그림6-6 의 BERT 임베딩 사각형에서 어떤 처리를 하는 것인지 설명 부탁드립니다!
#
- [x] 8. **p277**, 코드 6-31에선 전체 길이를 맞춘 후에 [CLS]와 [SEP]를 앞뒤로 붙이고 있는데 코드 순서대로 글을 표현하면 더 이해하기 쉬울 것 같습니다.
> 우선 워드피스 토크나이저로 형태소 분석한 배치 문장들 앞뒤에 문장 시작을 알리는 스페셜 토큰 [CLS]와 (...) 전체 길이를 맞춘 것이 token_sequence다.
#
- [ ] 9. **P280**, 코드 6-34가 잘 작동하지 않습니다..ㅜㅜ
![ch6 p280 bert 파인 튜닝 에러](https://user-images.githubusercontent.com/24364335/70058000-7885fc00-1621-11ea-8858-060419a5ed4a.png)
#
- [x] 10. **p282**
> 이를 t-SNE로 2차원**을** 줄이고 Bokeh로 시각화한다.
> 이를 t-SNE로 2차원**으로** 줄이고 Bokeh로 시각화한다.

*****
### 3장
- [ ] 11. **p105~106**, BPE 예측 과정 질문
![ch3 p106 bert tokenize](https://user-images.githubusercontent.com/24364335/70065040-cd2f7400-162d-11ea-87bb-a942f0692e95.png)
p106의 코드 3-27 FullTokenizer를 실행한 결과입니다. p105에서
> _는 해당 어절의 첫 번째 서브워드임을 나타내는 구분자다.
라고 설명하고 있는데 사진의 맨 마지막 "집에좀가자좀"을 예로 들면 중간 과정이
- '집에' '좀가자좀'
- '집에', '##좀', '가자좀'
- '집에', '##좀', '##가자', 좀'
- '집에', '##좀', '##가자', ##좀'
이렇게 되는건가요? 앞의 서브워드를 분리한 후 뒤쪽이 다시 또다른 어절이 되어 _가 첫 번째 서브워드라고 설명하고 있는 것 인지 첫 번째라고 표시한 것이 이해가 잘 되지 않습니다.

**Comment by ratsgo** [comment]
@SonHyeSeon 님 부족한 책인데 관심 가져주셔서 감사드립니다. 아래 8가지에 대해서는 말씀하신 대로 수정해 전자책과 정오표에 반영하겠습니다.

```
1. p207, "ELMo의 original 모델에서는 코드 5-27처럼 컨볼루션 연산을 시행한다" 의 표현이 매끄럽지 못한 것 같습니다 코드 5-27에서는 ELMo original 모델에서 사용하는 필터 설정을 나타내고 있으므로 "ELMo의 original 모델에서는 코드 5-27의 필터들을 사용하여 컨볼루션 연산을 시행한다" 이런식으로 표현하면 좀 더 매끄럽지 않을까 생각합니다.
2. p207, "코드 5-27에서는 컨볼루션 필터를 일곱 종류를 쓰고 있다." 이 부분이 7종류를 모두 사용하는 것인지 7종류 중 선택하여 사용하는 것인지 의미가 모호한 것 같습니다. p208 부분을 보면 ELMo 모델의 경우 7종류를 모두 사용한다는 것으로 이해할 수 있는데 p207 부분의 표현에 그 내용을 추가해주시면 더욱 매끄럽게 이해될 것 같습니다.
3. p210, 수식2 하이웨이 네트워크 표기 오타
4. p212, 프리트레인 단계와 예측 단계의 구분이 프리트레인 단계에서도 예측 역할을 하는 손실 레이어가 있기 때문에 모호한 것 같습니다. 예측 단계를 파인 튜닝 단계등으로 표현하면 좀 더 이해가 쉬울 것 같습니다!
5. p246, 파일명 오타
6. p249, 코드 6-3 if is_training: 삭제. tune_utils.py를 확인해보면 log를 출력 하는 부분인 것 같아 삭제되어도 될 것 같습니다.
8. p277, 코드 6-31에선 전체 길이를 맞춘 후에 [CLS]와 [SEP]를 앞뒤로 붙이고 있는데 코드 순서대로 글을 표현하면 더 이해하기 쉬울 것 같습니다.
10. p282 오타
```

**Comment by ratsgo** [comment]
- **7. p273, BERT의 파인 튜닝에서 BERT 모델에 문장을 입력해 스페셜 토큰 [CLS]에 해당하는 벡터를 추출한다. 이 부분이 잘 이해가 되지 않습니다. 왜 전체 문장 벡터를 추출하지 않고 [CLS]벡터로만 파인 튜닝을 진행하는지, 그리고 P274의 그림6-6 의 BERT 임베딩 사각형에서 어떤 처리를 하는 것인지 설명 부탁드립니다!**
[BERT 논문 저자](https://arxiv.org/abs/1810.04805)들은 분류(classification) 과제를 파인튜닝할 때 [CLS] 벡터를 사용하고 있습니다. 이는 각 트랜스포머 레이어에서 문장 내 모든 단어 쌍 사이의 관계를 바라보도록 하는 self-attention 기법 덕분입니다. 맨 마지막 레이어의 [CLS] 벡터만 사용하더라도 해당 벡터에는 문장 내 모든 단어 쌍 간 관계가 농축되어 있습니다. 이와 관련해 BERT 논문에서는 다음과 같이 언급하고 있습니다.

<img width="400" alt="스크린샷 2019-12-05 오후 2 48 34" src="https://user-images.githubusercontent.com/26211652/70207525-61085980-176e-11ea-90ec-62c280139703.png">

**Comment by ratsgo** [comment]
- **11. p105~106, BPE 예측 과정 질문**
BERT가 BPE 기법으로 만든 vocabulary를 사용하긴 합니다만, SentencePiece 패키지와는 조금 다르게 씁니다. 책에서는 SentencePiece 패키지의 tokenize 결과를 설명했습니다. 다음과 같습니다.

<img width="500" alt="스크린샷 2019-12-05 오후 2 58 34" src="https://user-images.githubusercontent.com/26211652/70207994-bdb84400-176f-11ea-99d1-07194ccab9c8.png">

그런데 vocab이 같다고 가정할 때 BERT에서는 다음과 같이 토크나이즈 합니다.

```
학교, ##에서, 밥, ##을, 먹었, ##다
```

다시 말해 `##`로 시작하는 토큰은 이전 토큰과 한 어절(띄어쓰기 기준)에 있다는 뜻이고, `##`로 시작하지 않는 토큰은 어절에서 처음 등장하는 토큰이라는 뜻입니다. 그런데 설명하고 보니 SentencePiece 패키지 분석 결과를 BERT 코드의 FullTokenizer와 같이 설명하면 헷갈릴 염려가 있다는 생각이 들었습니다. 해당 내용이 헷갈리지 않도록 전자책과 정오표에 반영하겠습니다.

**Comment by ratsgo** [comment]
- **P280, 코드 6-34가 잘 작동하지 않습니다**
이 문제는 별도 이슈에서 다루겠습니다
