### ISSUE TITLE
BERTTuner.tune() 버그

### ISSUE THREAD

**Issue by hccho2** [ratsgo/embedding#57]
page 278-279. 코드 6-32
tune_utils.py에서 BERTTuner.tune() 함수를 보면,

```
tf.train.Saver(restore_vars).restore(sess, self.pretrain_model_fname)
saver = tf.train.Saver(max_to_keep=1)
sess.run(tf.global_variables_initializer())
```

이렇게 되어 있는데, pre-trained model을 restore 후, tf.global_variables_initializer()을 통해, 값을 다시 초기화 시키고 있습니다.
이렇게 되면, pre-trained model을 전혀 활용하지 못하는 버그입니다. 단순하지만, 모델에게는 치명적인...

다음과 같이, 수정이 필요합니다.

```
sess.run(tf.global_variables_initializer())
tf.train.Saver(restore_vars).restore(sess, self.pretrain_model_fname)
saver = tf.train.Saver(max_to_keep=1)
```

확인 부탁드립니다.

**Comment by ratsgo** [comment]
@hccho2 님 안녕하세요. 아래처럼 확인 결과 버그가 맞습니다. 제가 이렇게 번번이 신세를 지네요. 진심으로 감사드립니다. 다른 모델들도 확인해서 반영해 두겠습니다.

```python
import tensorflow as tf
from models.bert.modeling import BertModel, BertConfig

bertconfig_fname = "data-backup/sentence-embeddings/bert/multi_cased_L-12_H-768_A-12/bert_config.json"
pretrain_model_fname = "data-backup/sentence-embeddings/bert/multi_cased_L-12_H-768_A-12/bert_model.ckpt"
max_seq_length = 128

config = BertConfig.from_json_file(bertconfig_fname)
input_ids = tf.placeholder(tf.int32, [None, max_seq_length], name='inputs_ids')
input_mask = tf.placeholder(tf.int32, [None, max_seq_length], name='input_mask')
segment_ids = tf.placeholder(tf.int32, [None, max_seq_length], name='segment_ids')

model = BertModel(config=config,
                      is_training=True,
                      input_ids=input_ids,
                      input_mask=input_mask,
                      token_type_ids=segment_ids)

restore_vars = [v for v in tf.trainable_variables() if "bert" in v.name]
sess = tf.Session()
tf.train.Saver(restore_vars).restore(sess, pretrain_model_fname)

sess.run(model.embedding_table)

sess.run(tf.global_variables_initializer())
sess.run(model.embedding_table)
```

<img width="1357" alt="스크린샷 2019-12-10 오후 9 40 28" src="https://user-images.githubusercontent.com/26211652/70530304-f1430600-1b95-11ea-9ad1-b620b4c4a391.png">

**Comment by hccho2** [comment]
확인 감사합니다.

**Comment by ratsgo** [comment]
확인 결과 @hccho2 님 말씀하신 버그는 BERT와 XLNet에만 해당되는 것으로 나타났습니다. 이에 코드를 수정하였습니다. XLNet은 도서에서 제공하지는 않으나 본 레파지토리에 포함돼 있으므로 같이 수정하였습니다.

**Comment by ratsgo** [comment]
단어 임베딩 튜닝 모델은 해당 사항 없는 것으로 나타났습니다. `tf.global_variables_initializer()`을 실행한 뒤 pretraine된 단어 임베딩을 assign하기 때문입니다. 다음과 같습니다.

<img width="890" alt="스크린샷 2019-12-11 오전 11 21 42" src="https://user-images.githubusercontent.com/26211652/70585728-7c5ce400-1c08-11ea-8d84-024673f08312.png">

**Comment by ratsgo** [comment]
ELMo 튜닝 모델 역시 해당 사항 없는 것으로 나타났습니다. 아래 ELMo 관련 코드를 참고하시면 아시겠지만, ELMo는 자체 custom initializer를 사용하고 있기 때문입니다.

<img width="775" alt="스크린샷 2019-12-11 오전 11 11 46" src="https://user-images.githubusercontent.com/26211652/70585674-4455a100-1c08-11ea-9d9b-d34b6f074b3f.png">

실제로 아래 코드를 여러번 수행하더라도 동일한 결과가 나옵니다. pretrained weight가 잘 입력되고 있는 것 같습니다.

```python
import sys
sys.path.append('models')

import tensorflow as tf
from bilm import BidirectionalLanguageModel

options_fname = "data-backup/sentence-embeddings/elmo/pretrain-ckpt/options.json"
pretrain_model_fname = "data-backup/sentence-embeddings/elmo/pretrain-ckpt/elmo.model"
max_characters_per_token = 30

bilm = BidirectionalLanguageModel(options_fname, pretrain_model_fname)
ids_placeholder = tf.placeholder(tf.int32, shape=(None, None, max_characters_per_token), name='input')
labels_placeholder = tf.placeholder(tf.int32, shape=(None))
embeddings_op = bilm(ids_placeholder)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

# charater embeddings (CNN)
sess.run(list(bilm._graphs.values())[0].embedding_weights
```

**Comment by ratsgo** [comment]
다만 Allen AI 오리지날 코드상으로는 위의 ELMo BidirectionalLanguageModelGraph의 custom getter의 `kwargs[trainable]=False`로 되어 있는데요. 저도 `model.py`는 손대지 않는 것이 원칙이어서 수정하지 않았는데요.
오리지날 코드를 쓰게 되면 사실상 feature-based learning이 되어 버리는 것 같습니다. Fine-Tuning이라는 본연의 정의에 맞도록 `kwargs[trainable]=True`로 하는 것이 맞나 싶은데 @hccho2 님 의견은 어떠신가요?

**Comment by hccho2** [comment]
저는 코드 보면서,  embedding vector에 대해, weighted sum을 하는 방식이기  kwargs[trainable]=False로 두는 것이 더 무난해 보였습니다.  page 213의 수식 5-5에서 s_j 값이 trainable하기 때문에 pre-trained 모델의 취지에 어긋나지는 않는 것 같습니다.

다시 말해, 제 생각에는 kwargs[trainable]=False로 두는 것이 더 적절해 보입니다.


그리고, 제가 버그로 말씀드린 것은 Bert tune에 한정된 것이었습니다. Bert tune에서 버그를 확인하고,  word tune이나 ELMo tune쪽은 문제 없는 것으로 확인했었습니다.

**Comment by ratsgo** [comment]
@hccho2 님 의견 진심으로 감사드립니다!
