### ISSUE TITLE
page 303 수식33 확인

### ISSUE THREAD

**Issue by hccho2** [ratsgo/embedding#58]
page 303 수식33에서

a_k a_k^T = 1      ---> a_k^Ta_k=1
v_k v_k^T = 1      ---> v_k^Tv_k=1

이렇게 수정되어야 되지 않나요?
a_k, v_k를 열벡터로 표시하고 있으니까요.

**Comment by ratsgo** [comment]
@hccho2 님 맞습니다. 정오표와 전자책에 반영하겠습니다. 제보 감사드립니다.

**Comment by hccho2** [comment]
휼륭하신 책 잘 보았습니다. 대충 훓어보려고 시작했는데, 끝까지 보게되었네요^^
ELMo, BERT 모델 구조를 살펴볼 수 있어서, 개인적으로는 많은 도움이 되었습니다.

**Comment by ratsgo** [comment]
아닙니다 저야말로 @hccho2 덕분에 좀 더 엄밀한 책을 만들 수 있었습니다. 진심으로 감사드립니다^^
