### ISSUE TITLE
AWS Spot Instance에서 Docker가 안되는 문제가 발생합니다.

### ISSUE THREAD

**Issue by sbqsbqsbq** [ratsgo/embedding#61]
안녕하세요. 평소에 자연어 처리에 관심이 많고 현업에서도 사용하고 있는 직장인입니다. 다름이 아니라, 이번에 AWS 스팟 인스턴스(p2.xlarge / Deep Learning Base AMI (Ubuntu 16.04) Version 21.0)를 이용해서 기창님께서 올려주신 도커에 접속을 하려고 하는데 다음과 같은 에러가 나면서 접속이 되지 않습니다.

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\\\n\\\"\"": unknown.
```

CUDA 디바이스를 찾을 수 없다고 나오는데, CUDA 버전 체크를 해보면 CUDA가 10.0 버전으로 잘 나옵니다. 어떻게하면 문제를 해결할 수 있을까요?

**Comment by ratsgo** [comment]
안녕하세요 @sbqsbqsbq 님! 부족한 책인데 관심 가져주셔서 감사드립니다. 제가 확인한 결과 도서 본문에 제시된대로 `Deep Learning Base AMI (Ubuntu) Version 18.1`에서는 이상없이 동작함을 확인하였습니다. 

<img width="600" alt="스크린샷 2019-12-28 오후 3 44 27" src="https://user-images.githubusercontent.com/26211652/71540092-35e9e200-2989-11ea-993e-46abcc6e98d4.png">

spot instance를 생성하실 때 다음의 AMI로 지정하시면 문제 없이 작동할 거라 생각합니다.

- AMI 이름 : Deep Learning Base AMI (Ubuntu) Version 18.1
- AMI ID : ami-06c71bb88d9ada041
