### ISSUE TITLE
추가 질문 작성했습니다 :)

### ISSUE THREAD

**Issue by SimSuBeen** [ratsgo/embedding#62]
안녕하세요. 책을 구매하여 자연어 처리에 대해 공부를 하고 있는데, 코드를 작성하는 중 안되는 부분이 있어 여쭤보고자 글을 남깁니다. 

Ubuntu 18.10을 사용하여 올려주신 docker 링크를 들어가 docker를 설치하였습니다.
그 후에 
$ docker pull ratsgo/embedding-cpu
$ docker run -it --rm ratsgo/embedding-cpu bash
를 실행하였고, 

저는 책의 81쪽에 있는 한국어 위키백과 전처리를 실습해보려고 하였습니다. 
git pull origin master
bash preprocess.sh dump-raw-wiki
를 실행한 후 코드 3-2를 실행하는 도중에 오류가 발생하였는데,

wiki = WikiCorpus(in_f, tokenizer_func=tokenize)를 입력하였을 때
NameError: name 'tokenize' is not defined 라는 오류가 발생합니다. 

이를 어떻게 해결하여야 하는지 여쭤보고싶습니다. 

그리고, '/notebooks/embedding' 의 위치가 정확히 어디를 의미하는지 모르겠습니다.
제 Ubuntu의 embedding 폴더에 들어갈 경우 raw, processed 폴더가 없는데 이것이 맞는건지
아니면 잘못 된건지 알려주시면 감사하겠습니다.

책을 통하여 많은 배움을 얻고 있습니다. 감사합니다.

**Comment by ratsgo** [comment]
@SimSuBeen 님, 질문 감사드립니다. 질문 각각에 대해 말씀드리겠습니다.

**wiki = WikiCorpus(in_f, tokenizer_func=tokenize)를 입력하였을 때 NameError: name 'tokenize' is not defined 라는 오류가 발생합니다. 이를 어떻게 해결하여야 하는지 여쭤보고싶습니다.**
코드 3-2의 WikiCorpus 클래스가 사용하는 `tokenize` 함수가 정의되지 않아서 생기는 오류인 것으로 보입니다. `tokenize` 함수는 코드 3-4에 정의되어 있는데요. 코드 3-4를 먼저 실행하신 뒤 코드 3-2를 실행하시면 문제가 없을 것 같습니다. 해당 함수는 다음 링크에서도 확인할 수 있습니다. 복사해서 붙여넣는 방식으로 실행해보셔요!

- https://github.com/ratsgo/embedding/blob/master/preprocess/dump.py

**'/notebooks/embedding' 의 위치가 정확히 어디를 의미하는지 모르겠습니다.**
`/notebooks/embedding`는 도커 컨테이너를 실행했을 때 초기 위치를 가리킵니다. 다음 캡처 화면은 도서(1장 개발환경 설정)에 제시된대로 AWS 인스턴스를 생성한 뒤 해당 인스턴스에 접속해 `docker pull ratsgo/embedding-cpu`와 `docker run -it --rm ratsgo/embedding-cpu bash`를 실행한 화면입니다.

<img width="600" alt="스크린샷 2019-12-28 오후 3 53 32" src="https://user-images.githubusercontent.com/26211652/71540161-48185000-298a-11ea-800f-789a8f46a341.png">

**제 Ubuntu의 embedding 폴더에 들어갈 경우 raw, processed 폴더가 없는데 이것이 맞는건지 아니면 잘못 된건지 알려주시면 감사하겠습니다.**
raw, processed 등 디렉토리는 원래 도커 이미지엔 존재하지 않고 다운로드 스크립트를 실행했을 때야 비로소 생성됩니다. 다음 스크립트를 수행해보세요. 각각의 스크립트 수행 역할은 도서 각 챕터에 설명돼 있습니다.

```bash
git pull origin master
bash preprocess.sh dump-waw-wiki
bash preprocess.sh dump-raw-korquad
bash preprocess.sh dump-raw-nsmc
bash preprocess.sh dump-blog
bash preprocess.sh dump-processed
bash preprocess.sh dump-tokenized
```

**Comment by SimSuBeen** [comment]
자세한 답변 감사합니다. 말씀해주신 대로 스크립트를 실행 한 후에 raw, processed 등의 디렉토리가 생성된 것을 확인하였고, 3-4 후에 3-2를 실행하였더니 오류는 발생하지 않지만, 
![13](https://user-images.githubusercontent.com/54827422/71649894-c2175300-2d55-11ea-8a62-18952891d3b7.PNG)
1시간이 가까이 되도록 위의 사진과 같은 상황에서 멈춰 있습니다. 이전에 발생하였던 오류는 발생하지 않았지만 다음 코드를 작성하지 못하여 어떻게 해야 하는지 알고 싶습니다. 이 부분에서 원래 시간이 많이 소요되나요?

그리고 한 가지 더 궁금한 것이 있는데,  우분투의 /notebooks/embedding 위치에서 스크립트를 실행하였을 때 data, raw, processed 등의 디렉토리가 생성된 것을 확인할 수 있지만
우분투의 쉘을 껐다 다시 실행했을 경우에는 디렉토리가 없는 것을 알 수있었습니다.
원래 코드를 실행하기 위해서는 매번 스크립트를 실행하여 코드를 작성해야 하나요?

감사합니다. 새해복 많이 받으세요!

**Comment by ratsgo** [comment]
안녕하세요, @SimSuBeen 님! 질문 주셔서 감사합니다. 순서대로 말씀드리겠습니다.

**1. WikiCorpus 부분에서 원래 시간이 많이 소요되나요?**
`WikiCorpus`는 처음 만들어질 때 선언부인 `___init___` 부분에서 전체 코퍼스에 대해 사전(dictionary)을 만들기 때문에 말씀 주신 것처럼 매우 느린 것이 맞습니다. 이에 `WikiCorpus` 선언부를 다음과 같이 변경하였습니다. (더미 dictionary를 입력하기 때문에, WikiCorpus가 사전 생성이 완료됐다고 보고 사전 생성 부분을 건너 뜁니다) 코드 개선에 도움을 주셔서 진심으로 고맙습니다.

```python
from gensim.corpora import WikiCorpus, Dictionary
wiki = WikiCorpus(in_f, tokenizer_func=tokenize, dictionary=Dictionary())
```

전체 코드를 다시 쓰면 다음과 같습니다. 복사해서 붙여 넣어서 실행해 보세요. 만일 좀 더 자주 출력 로그를 보고 싶으시다면 `i % 10000 == 0`에 들어가는 숫자를 1만 이하로 줄여보시면 됩니다.

```python
import re, json, glob, argparse
from gensim.corpora import WikiCorpus, Dictionary
from gensim.utils import to_unicode

in_f = "/notebooks/embedding/data/raw/kowiki-latest-pages-articles.xml.bz2" 
out_f = "/notebooks/embedding/data/processed/processed_wiki_ko.txt"
output = open(out_f, 'w')
WIKI_REMOVE_CHARS = re.compile("'+|(=+.{2,30}=+)|__TOC__|(ファイル:).+|:(en|de|it|fr|es|kr|zh|no|fi):|\n", re.UNICODE)
WIKI_SPACE_CHARS = re.compile("(\\s|゙|゚|　)+", re.UNICODE)
EMAIL_PATTERN = re.compile("(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)", re.UNICODE)
URL_PATTERN = re.compile("(ftp|http|https)?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+", re.UNICODE)
WIKI_REMOVE_TOKEN_CHARS = re.compile("(\\*$|:$|^파일:.+|^;)", re.UNICODE)
MULTIPLE_SPACES = re.compile(' +', re.UNICODE)

def tokenize(content, token_min_len=2, token_max_len=100, lower=True):
    content = re.sub(EMAIL_PATTERN, ' ', content)  # remove email pattern
    content = re.sub(URL_PATTERN, ' ', content) # remove url pattern
    content = re.sub(WIKI_REMOVE_CHARS, ' ', content)  # remove unnecessary chars
    content = re.sub(WIKI_SPACE_CHARS, ' ', content)
    content = re.sub(MULTIPLE_SPACES, ' ', content)
    tokens = content.replace(", )", "").split(" ")
    result = []
    for token in tokens:
        if not token.startswith('_'):
            token_candidate = to_unicode(re.sub(WIKI_REMOVE_TOKEN_CHARS, '', token))
        else:
            token_candidate = ""
        if len(token_candidate) > 0:
            result.append(token_candidate)
    return result

wiki = WikiCorpus(in_f, tokenizer_func=tokenize, dictionary=Dictionary())

i = 0
for text in wiki.get_texts():
    output.write(bytes(' '.join(text), 'utf-8').decode('utf-8') + '\n')
    i = i + 1
    if (i % 10000 == 0):
        print('Processed ' + str(i) + ' articles')
output.close()
print('Processing complete!')
```

이런 처리가 번거로우실 경우 `/notebooks/embedding` 위치에서 다음 스크립트를 실행하시면 위와 동일하게 처리됩니다.

```bash
git pull origin master
bash preprocess.sh process-wiki
```

**2. 자원을 매번 새로 다운로드받아야 하나요?**
결론부터 말씀드리면 맞습니다. 도커 컨테이너에 말뭉치와 임베딩 등 리소스를 같이 포함하는게 부적절하다고 판단했기 때문인데요. 하나 팁을 드리면 다음과 같습니다.
도커 컨테이너에서 `exit`로 종료하면 컨테이너가 사라집니다. 그런데 `Ctrl+P`를 누르신 후 `Ctrl+Q`를 누르면 컨테이너를 계속 백그라운드에 띄워놓을 수 있습니다. 그러면 컨테이너가 죽지 않는 한 말뭉치, 임베딩 등 리소스를 반복적으로 다운로드할 필요가 없겠죠. 다음은 제 환경에서 실행해본 예시입니다.
우선 우분투 쉘에서 `docker ps`를 입력해보면 컨테이너가 아무것도 없습니다.

<img width="1000" alt="스크린샷 2020-01-11 오후 6 01 23" src="https://user-images.githubusercontent.com/26211652/72201944-357b3c00-349d-11ea-91f2-b7cc9aabd8b9.png">

GPU용 컨테이너를 실행합니다. 이후 `touch a` 명령어를 입력합니다. 이는 빈 파일을 만드는 명령인데요. `a`라는 파일은 다운로드한 말뭉치라고 가정해도 되겠습니다. 이후 `Ctrl+P`+`Ctrl+Q`로 컨테이너에서 빠져나옵니다.

<img width="955" alt="스크린샷 2020-01-11 오후 6 01 49" src="https://user-images.githubusercontent.com/26211652/72201957-5e033600-349d-11ea-9573-99638bcab7de.png">

다시 우분투 쉘에서 `docker ps`를 쳐봅시다. 방금 만든 컨테이너가 살아있음을 확인할 수 있습니다.

<img width="1000" alt="스크린샷 2020-01-11 오후 6 02 29" src="https://user-images.githubusercontent.com/26211652/72201975-90149800-349d-11ea-81a2-978c09c704c3.png">

그러면 다시 컨테이너에 접속해볼까요? `docker attach container_id`를 입력하면 됩니다. 이후 파일 목록을 확인하는 명령어 `ll`을 치면 아까 만들었던 `a` 파일이 그대로 있는 걸 확인할 수 있습니다.

<img width="708" alt="스크린샷 2020-01-11 오후 6 02 57" src="https://user-images.githubusercontent.com/26211652/72201988-c5b98100-349d-11ea-96a9-9a60ba1ce8b7.png">

컨테이너를 정말로 종료하고 싶을 때는 `exit`를 치면 됩니다. 이후 우분투 쉘에서 `docker ps`를 치면 해당 컨테이너가 사라졌음을 확인할 수 있습니다.

**3. jupyter notebook이나 idle을 실행시켜 python을 사용할 수 있을까요?**
도커 컨테이너 내에서 주피터 노트북 등을 사용하는 방법은 이전부터 문의가 있었는데 제가 아직은 도커 쪽은 문외한이라 알아보고 있는 중입니다. 혹시 이 글 보시는 재야의 무림 고수분께서 팁을 공유해주시면 진심으로 감사하겠습니다.

**Comment by SimSuBeen** [comment]
친절하고 자세한 답변 너무 감사합니다. 아직 배우고 있는 대학생이라 여쭤볼 게 많은 점 이해 부탁드립니다. 
한 가지 더 여쭤볼 게 있는데,

저는 현재 virtualbox와 vmware 를 사용하고 있습니다.
virtualbox, vmware에 ubuntu 18.04를 설치하였고,  그 위에 docker를 설치하였습니다. 

nvidia-docker를 사용하고 싶은데 이를 설치하는 과정에서 끊임 없는 오류가 발생합니다. 
docker 설치 튜토리얼을 보면, nvidia-docker를 설치하고자 할 때엔 호스트 운영체제에 NVIDIA 드라이버가 설치되어 있다고 나와있는데, 
가상머신의 ubuntu에서 nvidia-docker를 설치할 경우 오류가 발생하여 nvidia-docker 설치가 안됩니다. 이런 문제가 vmware나 virtualbox 위에서 ubuntu를 사용하여 문제가 발생하는 것인지 궁금합니다.
ubuntu가 독자적인 os일 경우에만 nvidia-docker 사용이 가능한 것인가요?
virtualbox나 vmware위에서 ubuntu를 사용한다면 이 때는 nvidia-docker를 사용할 수 없는 건가요?

책을 구매하고 약 한달이라는 시간동안 이 문제를 해결하지 못하고 있어서 혹시나 도움을 구할 수 있지 않을까 하여 글을 남깁니다. 아직 배우기 시작한지 얼마 안된 학생이라 모르는 게 많은 점 이해부탁드립니다. 감사합니다.

**Comment by mwmw7** [comment]
> 경우에만 nvidia-docker 사용이 가능한 것인가요?
> virtualbox나 vmware위에서 ubuntu를 사용한다면 이 때는 nvidia-docker를 사용할 수 없는 건가요?
> 
> 책을 구매하고 약 한달이라는 시간동안 이 문제를 해결하지 못하고 있어서 혹시나 도움을 구할 수 있지 않을까 하여 글을 남깁니다. 아직 배우기 시작한지 얼마 안된 학생이라 모르는 게 많은 점 이해부탁드립니다. 감사합니다.
 
저는 물리적 머신에 NVIDIA RTX 2070 설치되어있는 상황에서 nvidia-docker 설치하고 잘 작동하네요

**Comment by ratsgo** [comment]
@mwmw7 님 제가 없는 사이 대신 답해주셔서 감사드립니다. 제가 알기로는 **nvidia-docker는 윈도우를 지원하지 않습니다([참고](https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#is-microsoft-windows-supported))** 도서에 제시된대로 아마존 웹 서비스(AWS)를 활용해 개발환경을 구축하는 걸 추천해 드립니다. AWS 사용 방법은 [이곳](https://drive.google.com/open?id=1Zo7_F-ruU5NW9YtAR8IE2zKzm5lz_Cz7)을 참고하세요.

**Comment by ratsgo** [comment]
이슈 주제는 구체적일 수록 관리/검색하기 좋다고 생각하는데요. @SimSuBeen 님 혹시 추가 질문이 있으시면 별도 이슈로 남겨주시면 답변해 드리겠습니다. 감사합니다.

**Comment by mwmw7** [comment]
참고로 저도 우분트 18.04 사용중입니다.
