### ISSUE TITLE
Bert모델에서 'pooler' 부분 구현 문의

### ISSUE THREAD

**Issue by jihobak** [ratsgo/embedding#63]
https://github.com/ratsgo/embedding/blob/dc3560d79382ab03669a13df4bcbe87ab05aa88c/models/bert/modeling.py#L227

여기서 first_token_tensor = self.sequence_output[:, 0, :] 대신에 tf.squeeze를 사용한 특별한 이유가 있을까요?

**Comment by ratsgo** [comment]
@jihobak 님, 안녕하세요. 질문 감사드립니다. `modeling.py`에 정의된 코드는 BERT 저자들이 직접 작성한 것으로 저로서도 추측으로밖에 답변을 드리지 못할 것 같은데요. 제 생각에도 @jihobak 님이 말씀하신 것처럼 `self.sequence_output[:, 0, :] `으로 처리하나, 코드대로 `tf.squeeze(self.sequence_output[:, 0:1, :], axis=1) `로 처리하나 동일한 결과가 나올 것 같다는 생각입니다. 다음을 참고하시면 좋을 것 같습니다(batch_size=10, seqeunce_length=128, hidden_dimension=768로 가정).

<img width="600" alt="스크린샷 2019-12-28 오후 4 32 35" src="https://user-images.githubusercontent.com/26211652/71540588-0ab6c100-2990-11ea-8e74-b9b8b44bd4b9.png">


다만 도서에는 코드에 명백한 버그가 아닌 한 저자 코드를 그대로 사용하는 것이 좋을 것 같은데 @jihobak 님 생각은 어떠신지요?

**Comment by jihobak** [comment]
@ratsgo tf.squeeze가 low-level단에서 더 효율적으로 쓰이는걸까요??ㅎㅎ 저자님의 의견에 동의합니다~! 답변 감사드립니다. ^^;

**Comment by ratsgo** [comment]
흠, 저도 @jihobak 님이 의견 주신 것처럼 `sequence_output[:, 0, :]`이 더 효율적이어 보이는데요. 대가들이 짠 코드이니 더 깊은 맥락이 있겠거니 생각하고 있습니다^^; BERT 공식 리포지토리에 이슈업해보시는 건 어떨지요? 여기서는 일단은 저자 코드 그대로 두겠습니다. 다시 한번 감사드립니다.

**Comment by jihobak** [comment]
@ratsgo 이슈업 했습니다. 혹시나 생각하지 못한 부분이있을 수 있으므로, 공식repo에서 답변이후에 close하겠습니다. 감사합니다. ^^

**Comment by ratsgo** [comment]
시간이 많이 지나 일단 이슈 클로즈합니다. 진전사항은 별도 이슈에 기록해주세요.
