### ISSUE TITLE
BERT 모델에서 'attetion_ouput' 코드 문의

### ISSUE THREAD

**Issue by jihobak** [ratsgo/embedding#64]
https://github.com/ratsgo/embedding/blob/dc3560d79382ab03669a13df4bcbe87ab05aa88c/models/bert/modeling.py#L856
이부분의 주석에 
```python
# In the case where we have other sequences, we just concatenate
# them to the self-attention head before the projection.
```
이라고 해주셨는데, 원래 default는 각 batch마다 만약 한 문장이이지만 만약 각 batch마다 두 문장이였다면 각각의 문장에대한 attention_output을 concat 해서 사용한다. 라고 받아들였습니다. 
그런데 그런경우가 현재 코드상에서 일어날수 있는 부분인지 의문이 들어서 질문을하게 되었습니다.

이어서 말씀드리면 

https://github.com/ratsgo/embedding/blob/dc3560d79382ab03669a13df4bcbe87ab05aa88c/models/bert/modeling.py#L832-L852
에서
이 부분은 항상 참 아닌가요?
https://github.com/ratsgo/embedding/blob/dc3560d79382ab03669a13df4bcbe87ab05aa88c/models/bert/modeling.py#L851

```python
attention_heads.append(attention_head) 는 각 layer 마다 한 번 만 일어나게 되고
attention_heads = [ (attention head), ] 이렇게 될것 같은데...
```

좋은책 감사합니다.

**Comment by ratsgo** [comment]
@jihobak 님 질문 감사드립니다. 네 이해하신 것처럼 저도 이해하고 있습니다. 다만 transformer 저자들은 multi-head attention 이외에 다른 어텐션 결과들도 같이 활용할 수 있음을 염두에 두고 코드를 작성한게 아닌가 합니다(BERT 저자들은 transformer block은 Attention is All you need 논문을 그대로 활용했다고 언급하고 있습니다). 예컨대 다음과 같습니다.

- multi-head attention만 반영하는 경우
```
# attention_head = Q, K, V에 multi-head attention 실시하고 concat한 결과
attention_heads = [attention_head]
```

- multi-head attention + custom attention
```
# attention_head = Q, K, V에 multi-head attention 실시하고 concat한 결과
# custom_head1 = Q, K, V에 사용자가 지정한 attention을 실시한 결과
# ...
# custom_headn = Q, K, V에 사용자가 지정한 attention을 실시한 결과
attention_heads = [attention_head, custom_head1, ..., custom_headn]
```

혹시 제가 잘못 이해하고 있거나 첨언할 점 있으시면 말씀해주세요. 다시 한번 감사드립니다.

**Comment by ratsgo** [comment]
아 그리고 다음 statement에 대해서는 제가 조금 다른 견해를 가지고 있는데요. 이 부분에 대해서도 의견 주시면 좋을 것 같습니다.

**원래 default는 각 batch마다 만약 한 문장이이지만 만약 각 batch마다 두 문장이였다면 각각의 문장에대한 attention_output을 concat 해서 사용한다. 라고 받아들였습니다.**
pretrain을 할 때 batch 하나당 문장 2개가 들어갑니다. `[CLS] Sent_A [SEP] Sent_B [SEP]` 이런 식입니다. 그런데 `attention_output`을 계산한 결과는 2개가 아니라 1개로 알고 있습니다(해당 배치의 토큰 시퀀스 1개에 대해 multi-head attention를 실시하고 concat한 결과)
