### ISSUE TITLE
정오표 페이지 오류

### ISSUE THREAD

**Issue by HC-JEONG** [ratsgo/embedding#66]
P. 265가 두 개 있습니다. 내용을 보면 코드 6-7, 코드 6-18인데 코드 6-7에 해당 정오 내용은 254~255 페이지에 있으므로 수정해줘야합니다.
![캡처](https://user-images.githubusercontent.com/51831391/71664785-b485bb80-2d9d-11ea-8e46-e8ef4a18a8f5.JPG)

**Comment by ratsgo** [comment]
@HC-JEONG 님, 말씀하신 것이 맞습니다. 의견주신대로 수정하였습니다. 정오표까지 봐주시니 부끄러움과 감사함이 교차하네요. 진심으로 고맙습니다.
