### ISSUE TITLE
101p 은전한닢 사용자 사전 추가 내용 오류

### ISSUE THREAD

**Issue by lazineer** [ratsgo/embedding#67]
안녕하세요. 책 잘 보고 있습니다.
101p 그림 3-15 내용에 오류가 있어서 제보드립니다.
mecab-user-dic.csv를 보니 책과 내용이 다르네요.

`가우스전자,,,,NNP,**,T,가우스전자,**,**,**,**,**`
를 아래와 같이 수정 필요합니다.
`가우스전자,,,,NNP,*,T,가우스전자,*,*,*,*,*`

1쇄 구매했는데 오타가 정말 많네요 ㅠㅠ

**Comment by ratsgo** [comment]
@lazineer 님 의견 감사드립니다. 정오표에 반영하였습니다. 오타와 오류는 잡는다고 잡았습니다만 발간 이후에도 계속 보여서 정말 죄송스러운 마음입니다. 더 좋은 컨텐츠로 보답하겠습니다.
