### ISSUE TITLE
코드 4-4, 4-27 오류

### ISSUE THREAD

**Issue by TransAmRaiser** [ratsgo/embedding#68]
1. 코드 4-4
디렉토리 생성 부분이 누락되어 있어 오류가 발생합니다. 한참을 헤매다가 뒤에 있는 코드들을 보고 디렉토리 생성이 필요하다는 것을 알게 되었습니다. 다음과 같은 코드를 추가해 주시기를 바랍니다.

mkdir -p data/word-embeddings/word2vec

2. 코드 4-27
WordEmbeddingEvaluator의 첫 번째 인수가 잘못되어 오류가 발생합니다. glove.txt라는 파일이 없다는 오류가 발생하는데, 해당 경로로 가 보니 그와 비슷한 이름의 "glove.vecs.txt"라는 파일이 있더군요. 이것으로 첫 번째 인수를 수정하니 제대로 실행되었습니다. 코드 4-27을 수정하거나 glove.vecs.txt를 glove.txt가 되도록 이전 코드들을 수정해야겠습니다.

**Comment by ratsgo** [comment]
@TransAmRaiser 님 안녕하세요. 부족한 책인데 관심 가져주셔서 감사드립니다. 

1번 관련 : 코드 4-4를 실행하면 [make_save_path](https://github.com/ratsgo/embedding/blob/15eec8dd70569f306f426e819945d95711da2818/models/word_utils.py#L259) 함수를 호출해 해당 디렉토리를 만들게 되어 있습니다. 제 생각에는 도커 컨테이너가 아닌 환경에서 작업하셔서 그런 것 같은데요. 상대 경로를 입력하면 절대 경로를 인식하도록 코드를 개선하겠습니다. 다음처럼 최신 코드를 받아 실행하시길 권해드립니다.

```bash
git pull origin master
cd /notebooks/embedding
python models/word_utils.py --method train_word2vec --input_path data/tokenized/corpus_mecab.txt --output_path data/word-embeddings/word2vec/word2vec
```

2번 관련 : glove 수행 결과는 코드 4-26의 마지막 라인의 `save-file` 인자에 확장자가 `txt`인 형태입니다. 기존은 `data/word-embeddings/glove/glove.vec`로 되어 있는데요. 코드 4-26을 수행하고 코드 4-27을 실행하면 말씀주신 것처럼 오류가 납니다. 코드 4-32(이미 학습된 단어 임베딩 다운로드)를 수행하고 코드 4-27을 실행하면 잘 됩니다. 말씀주신 것처럼 통일하기 위해 코드 4-25의 `save-file` 인자를 다음과 같이 고치겠습니다.

```
-save-file data/word-embeddings/glove/glove.vecs
>
-save-file data/word-embeddings/glove/glove
```

**Comment by ratsgo** [comment]
1번과 관련해서 생각해보니 예상치 못한 경우의 수로 임베딩을 저장할 디렉토리가 없어서, 임베딩을 다 만들었는데 쓰지 못하고 죽는 케이스가 있을 수 있겠네요. 말씀하신 것처럼 `mkdir -p data/word-embeddings/word2vec`도 코드 4-4에 추가해 놓겠습니다. 제보 다시 한번 감사드립니다.
