### ISSUE TITLE
도커 컨테이너 실행 오류

### ISSUE THREAD

**Issue by geumjaelee** [ratsgo/embedding#69]
종이책 48p. 
코드 1-2 GPU 환경 도커 컨테이너 띄우기 항목에서

docker run -it --rm --runtime=nvidia ratsgo/embedding-gpu bash
를 실행시키면 아래의 오류가 발생하며 실행되지 않는데, 
Error response from daemon: Unknown runtime specified nvidia.
See 'docker run --help'.

대신
docker run -it --rm --gpus all ratsgo/embedding-gpu bash
로 바꾸면 실행은 됩니다. 

정확히 기억은 나지 않는데, 경로 설정이 잘못 되어서 그런거라고 어느 게시판에서 그랬던 것 같네요.
좀 걱정인 것은 이렇게 바꿔서 다른 기능이 정상 실행이 안 될 가능성입니다.
해당 이슈 잘 아시는 분 있으면 의견 바랍니다.

![Deepin스크린샷_select-area_20200114155304](https://user-images.githubusercontent.com/24272342/72321009-263aff00-36e6-11ea-85e1-399c3bb2af14.jpg)

**Comment by mwmw7** [comment]
nvidia 도커가 업데이트 되서 옵션이 변경됬다고 하더라구요 저도 저렇게 사용중

**Comment by ratsgo** [comment]
@geumjaelee @mwmw7 님 제가 없는 사이에 해결책을 찾아주셔서 진심으로 감사드립니다. 전자책, 정오표 등에도 반영해 두겠습니다.
