### ISSUE TITLE
smart_open_lib.py:398: UserWarning: This function is deprecated, use smart_open.open instead.

### ISSUE THREAD

**Issue by mwmw7** [ratsgo/embedding#70]
127페이지 
코드 4-5 페이지 실행중 발생하는 에러 입니다.
/usr/local/lib/python3.5/dist-packages/smart_open/smart_open_lib.py:398: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL

**Comment by mwmw7** [comment]
하지만 jupyter nootebok 에서는 는 결과는 보이네요
![image](https://user-images.githubusercontent.com/1140031/72416875-fe699b00-37ba-11ea-880d-21caf5ef5b14.png)

**Comment by bohyunshin** [comment]
안녕하세요. 이것과 다른 얘기이긴 한데, 혹시 두번째 사진이 도커 환경에서 쥬피터 노트북 접속하신 것인가요? 맞다면, 어떻게 하셨는지 대략적으로라도 알려주실수 있을까요? 제 능력 부족으로 이에 대해서 찾아보고 시도해보다가 결국 실패해서 ratsgo님이 제공해주신 도커가 아니라 제 로컬에서 공부하고 있어서 불편함이 있거든요,,,
답변해주시면 감사하겠습니다.

**Comment by ratsgo** [comment]
@mwmw7 님 혹시 파이썬 콘솔에서는 결과가 제대로 출력이 안되나요? 제가 알기로는 해당 warning은 결과 출력에는 영향을 끼치지 않습니다만.. 다만 신경쓰일 수 있으므로 해당 warning이 뜨지 않도록 추후 코드를 수정해 두겠습니다.

**Comment by mwmw7** [comment]
@ratsgo warning 만뜨네요^^
