### ISSUE TITLE
궁금증 및 오류 질문드립니다!

### ISSUE THREAD

**Issue by bohyunshin** [ratsgo/embedding#72]
안녕하세요 좋은 책 써주셔서 감사합니다.
열심히 공부하고 있는 학생입니다.

먼저 궁금한 사항입니다.
개인적인 이유로 제공해주신 도커를 사용하지 않고 제 노트북 환경으로 코드들을 진행하고 있습니다.
그러던 도중에, word embedding을 평가하는 함수로
from models.word_eval import WordEmbeddingEvaluator
가 자주 등장하는데요, 구글링을 해보아도 해당 함수가 잘 찾아지지 않아서 질문 드립니다.

혹시 이 함수는 ratsgo님께서 직접 작성하신 함수인가요?? 제 로컬에서 사용하고 싶은데, 어디서 설치를 하면 될까요?..  pip install models을 해도 설치가 안됩니다!...
답변 부탁드리겠습니다. 감사합니다.

다음으로 오류 관련 질문입니다.
제 노트북 환경으로 진행하는 것에 한계를 느껴 도커에 접속하여 코드를 따라하려고 하는데요, 코드 4-1을 따라하니까 아래와 같이 tokenized.zip을 찾을 수 없다고 뜹니다. 다른 이전의 다른 bash 명령어는 잘 작동했는데 얘만 이런 오류가 뜨네요. 혹시 해결책 알려주실수 있을까요?

![image](https://user-images.githubusercontent.com/36855000/73603878-ddcb7e80-45cb-11ea-89e5-588c71450231.png)

**Comment by ratsgo** [comment]
@bohyunshin 님 안녕하세요. 부족한 책인데 관심 가져주셔서 감사드립니다. 순서대로 제가 아는대로 답변 드리겠습니다.

- **WordEmbeddingEvaluator 설치 방법** 
`WordEmbeddingEvaluator` 클래스는 제가 직접 작성한 것입니다. 이 repository를 clone 받으시면 `embedding/models/word_eval.py`에서 해당 클래스를 찾아보실 수 있습니다. 클론 방법은 내려받으려는 디렉토리에서 `git clone https://github.com/ratsgo/embedding.git`를 수행하시면 됩니다. 해당 클래스 코드가 궁금하시면 다음 링크를 참고하세요 : https://github.com/ratsgo/embedding/blob/master/models/word_eval.py
- **bash preprocess.sh dump-tokenized 관련** 
제 환경에서 수행했을 때는 문제없이 작동을 하는데요. 두 가지 해결방안 권해드립니다. (1) `embedding/data/tokenized.zip` 파일을 지우고 `bash preprocess.sh dump-tokenized`를 다시 실행해 보세요. (2) 파일을 다른 방식으로 다운로드받아 보세요. 다음 이슈 참고하시면 됩니다 : https://github.com/ratsgo/embedding/issues/47#issuecomment-561943391

**Comment by bohyunshin** [comment]
답변감사합니다.
첫 번째 답변은 해결됐습니다.
두 번째 답변에서 궁금한점이 있는데요. 제가 docker나 우분투에 익숙하지 않아서요. 양해부탁드립니다.
저자님께서 첫 번째 방안으로 embedding/data/tokenized.zip을 지우라고 하셨는데, 
bash preprocess.sh dump-tokenized을 실행한 후에, data 폴더까지 생기긴하는데 tokenized.zip은 생기지 않습니다. 즉, 삭제할 tokenized.zip이 없습니다!..
두 번째 답변은 의도하신 것이, 파일을 저의 로컬에서 다운 받은 후에 도커 컨테이너로 옮겨보라는 말씀이신지 궁금합니다.
감사합니다.

**Comment by ratsgo** [comment]
@bohyunshin 님 아래 명령어를 실행해 보시겠어요?

```bash
gdrive_download 1Ybp_DmzNEpsBrUKZ1-NoPDzCMO39f-fx /notebooks/embedding/data/tokenized.zip
```

**Comment by bohyunshin** [comment]
답변 감사드립니다.
알려주신 그대로 실행했떠니 아래와 같이 tokenized.zip이 생겼습니다. 
![image](https://user-images.githubusercontent.com/36855000/73608532-ada1d100-4607-11ea-9040-06e96d60fbb7.png)

하지만  동동일하게 위와 같은 오류가 뜹니다. 게다가 bash preprocess.sh dump-tokenized을 실행하고 ./data로 가보니까 ./data에 있는 tokenized.zip가 사라져있었습니다..

그래서 링크걸어주신 답변도 동일하게 따라해보았습니다.
이것도 동일하게 tokenized.zip은 생기는데 bash preprocess.sh dump-tokenized에서 동일한 오류가 발생했습니다.

혹시 제가 무엇을 잘못하고있는것일까요?.. 저는 윈도우 유저라서 cmd에서 docker에 접속했습니다.
cmd을 키고
docker pull ratsgo/embedding-cpu
docker run -it --rm ratsgo/embedding-cpu bash
을 통해 도커에 접속했습니다.

그런데 bash preprocess.sh dump-raw-wiki 얘는 또 실행이 되거든요,,
docker 자체가 환경에 구애받지 않기 위해서 사용하는 것으로 알고있는데 제가 무엇인가를 잘못하고있는것같기도하네요,,

**Comment by ratsgo** [comment]
@bohyunshin 님, `preprocess.sh ` 스크립트는 [링크](https://github.com/ratsgo/embedding/issues/47#issuecomment-561943391)에 나와있는 수행과는 별개여서요. 아래처럼 수행해보시면 어떨까 싶습니다.

```bash
git clone https://github.com/chentinghao/download_google_drive.git
pip install tqdm
cd download_google_drive
python download_gdrive.py 1Ybp_DmzNEpsBrUKZ1-NoPDzCMO39f-fx tokenized.zip
```

위와 같이 수행하면 `/notebooks/embedding/download_google_drive` 경로에 `tokenized.zip` 파일이 생성됩니다. 제가 우분투 환경에서 도커를 띄워서 확인한 결과 이상 없이 동작함을 확인했습니다.
