### ISSUE TITLE
p.40 영문 표기 오타

### ISSUE THREAD

**Issue by karl6885** [ratsgo/embedding#76]
안녕하세요. 좋은 책으로 즐겁게 공부하고 있습니다. 감사합니다.

사소하지만 40페이지에서 오타를 발견하여 이슈 올립니다.

sequence-to-**sequenece**  -> sequence-to-**sequence**

오늘도 좋은 하루 보내세요.

**Comment by ratsgo** [comment]
안녕하세요 @karl6885 님! 오타 정정 이슈 올려주셔서 감사드립니다. 해당 오타는 2쇄 이후에 정정되었는데요. 정오표에 반영해 두겠습니다. 다시 한번 감사드립니다.
