### ISSUE TITLE
309, 315p 오류

### ISSUE THREAD

**Issue by sftblw** [ratsgo/embedding#77]
## 309p 두 번째 문단

> 정규분포는 특성값이 연속적인 무한모집단 분포의 일종으로서 평균이 **(내용 없음)** 이고 표준편차가 **(내용 없음)** 인 경우 (생략)

문맥상 평균이 mu, 표준편차가 theta 인 것 같습니다. 편집 오류인지 기호가 안 나와있습니다. 아니면 이건 알라딘 전자책 뷰어 버그일 수도 있을 것 같네요. 다른 전자책에도 동일한 현상이 있으면 알라딘 쪽에 보고하겠습니다.

## 315p 마지막 문단

> DAG는 **깊이** 우선 탐색(Breath First Search) (생략)

문맥상 깊이 우선 탐색이 아니라 너비 우선 탐색 같습니다. 해당 문단의 다른 부분에도 깊이 우선 탐색이라고 표시된 부분이 있습니다.

**Comment by ratsgo** [comment]
@sftblw 님 오류 제보 감사드립니다. 315페이지와 관련해 정오표에 반영하겠습니다. 309페이지와 관련해서는 전자책에 반영된 것으로 알고 있는데요. 309페이지와 관련해 출판사 쪽에 편집 기호가 사라지지 않도록 알리겠습니다.
