### ISSUE TITLE
혹시 3쇄나 그 후라도 Tensorflow 2.x 버전으로 변경하실 계획이 있나요?

### ISSUE THREAD

**Issue by yjkim0083** [ratsgo/embedding#79]
안녕하세요 NLP를 공부중에 저자님의 블로그에서 많은 도움을 받고 있습니다. 
이자리를 빌어 감사드립니다 😄 

다름이 아니고 TF v2가 발표되었고, Keras 기반의 API를 사용하여 코딩을 하다보니 TF v1.x 보단 매우 간결하고 이해하기 쉽게 업데이트 되었다고 생각합니다.

해당 책의 코드를 TF v2로 바뀌서 출판할 계획이 있으신지 문의를 드립니다.

**Comment by ratsgo** [comment]
@yjkim0083 님 부족한 책인데 관심 가져주셔서 감사드립니다. [파이토치](https://github.com/ratsgo/embedding/issues/22) 포팅에 대한 요청도 있었는데요. 리포 전체를 손봐야 하는 방대한 작업이라 아직은 계획이 없습니다만, 염두에 두도록 하겠습니다. 물론 무림 고수분들의 풀리퀘스트 역시 환영합니다.
