### ISSUE TITLE
안녕하세요 한국어 임베딩 책에 대해 질문 있어서 문의드립니다.

### ISSUE THREAD

**Issue by HojinHwang** [ratsgo/embedding#80]
안녕하세요 작가님 . 한국어 임베딩 책을 구매하여 공부하고 있는 대학생입니다. 
해결되지 않는 점이 있어서 문의드립니다.
docker 다운로드 완료했는데 책의 코드 3-1를 docker에서 실행하면 New State of 'nil' is invalid 라는 문장의 오류가 뜨면서 data가 다운되지 않습니다. 
어떻게 해결할 수 있을까요 ?

**Comment by HojinHwang** [comment]
위와 관련해서 질문 하나 더 하겠습니다 !

Docker ToolBox 가 설치된 경로와 embedding 설치된 경로가 달라서 코드 3-1 이 실행이 안되는 것일까요 ..?
docker에서 git 경로에 대한 레파지토리를 설치하려고 docker 실행 -> cd 입력 -> git clone 을 했는데 다른 경로로 설치가 되더라구요 ,, 해결책을 알 수 있을까 싶어서 질문드렸습니다 .. !

**Comment by ratsgo** [comment]
@HojinHwang 님 이슈 리포트 감사드립니다. `preprocess.sh` 스크립트와 별개로 데이터를 다운로드하는 방법이 하나 더 있습니다. 다음 링크를 참고하셨으면 좋겠습니다. 혹시 또 문제가 있으시면 알려주세요. [이 이슈](https://github.com/ratsgo/embedding/issues/72)와 병합 처리하겠습니다.

- https://github.com/ratsgo/embedding/issues/47#issuecomment-561943391
