### ISSUE TITLE
gdrivedownload 코드

### ISSUE THREAD

**Issue by gyunggyung** [ratsgo/embedding#83]
gdrivedownload 가 404 로 나옵니다.

https://drive.google.com/drive/u/0/folders/1kUecR7xO7bsHFmUI6AExtY5u2XXlObOG

**Comment by ratsgo** [comment]
@gyunggyung 님 이슈 감사드립니다. 혹시 `processed.zip` 파일을 보고 싶으신 거죠? 다음 링크에서 확인할 수 있습니다.

- https://drive.google.com/file/d/1kUecR7xO7bsHFmUI6AExtY5u2XXlObOG

**Comment by gyunggyung** [comment]
감사합니다!!~!!
