### ISSUE TITLE
BERT  파인튜닝 오류

### ISSUE THREAD

**Issue by kimsse0430** [ratsgo/embedding#92]
colab에서 수행중입니다.
버트 파인튜닝을 위해 아래와 같은 명령문 수행시 
!bash sentmodel.sh tune-bert

tune BERT...
nohup: redirecting stderr to stdout 이렇게만 나오고 아무런 액션이 일어나지 않습니다.

**Comment by ratsgo** [comment]
너무 답이 늦어 죄송합니다.
해당 메세지는 실행 스크립트가 백그라운드에서 실행되며 그 결과는 log에 기록된다는 뜻입니다.
실행하고 있는 디렉토리의 root에서 로그를 확인하실 수 있을 것 같습니다.
다만 이 책 튜토리얼은 colab 환경을 염두에 두지 않아서 그 확인이 다소 어려울 것 같은데요ㅠㅠ
아직은 colab 지원 계획이 없습니다. 큰 도움이 못되드려 죄송합니다.
