### ISSUE TITLE
3쇄 149p 오류

### ISSUE THREAD

**Issue by 2CHAN0** [ratsgo/embedding#93]
4.6.1 모델 기본 구조 149p
둘째 문단의 3~4번째 줄에 오류가 있어보입니다.

f(xij)가 클수록 Ui,**Uj** 벡터 간 내적값이 실제 PMI 값과 좀 더 비슷해야 학습 손실이 줄어든다.
=> f(xij)가 클수록 Ui,**Vj** 벡터 간 내적값이 실제 PMI 값과 좀 더 비슷해야 학습 손실이 줄어든다.

3쇄 발행 본 | 2020년 2월 11일

**Comment by ratsgo** [comment]
@2CHAN0 님 안녕하세요. 지적하신 내용이 맞습니다. 정말 감사드립니다.
해당 오타는 3쇄 인쇄본에만 존재하는 것으로, 정오표에도 기재하였습니다.
이후 출판 원고와 전자책에도 반영해 두겠습니다.
