### ISSUE TITLE
docker 설치 및 컨테이너 실행

### ISSUE THREAD

**Issue by ldahee** [ratsgo/embedding#94]
안녕하세요. 도커 설치 후 컨테이너 실행하는 과정에서 에러가 발생해서 글 남깁니다.

![image](https://user-images.githubusercontent.com/41093239/82452791-afc26980-9aea-11ea-94c6-7d1c380665ee.png)

맨 마지막 명령어를 입력하면 다음과 같은 에러가 뜹니다.

![image](https://user-images.githubusercontent.com/41093239/82452903-cf599200-9aea-11ea-8de0-ab44bcea6d6e.png)

도커를 재시작한 후 다시 실행해도 똑같은데 다른 해결방법이 있을까요?

**Comment by ldahee** [comment]
> 안녕하세요. 도커 설치 후 컨테이너 실행하는 과정에서 에러가 발생해서 글 남깁니다.
> 
> ![image](https://user-images.githubusercontent.com/41093239/82452791-afc26980-9aea-11ea-94c6-7d1c380665ee.png)
> 
> 맨 마지막 명령어를 입력하면 다음과 같은 에러가 뜹니다.
> 
> ![image](https://user-images.githubusercontent.com/41093239/82452903-cf599200-9aea-11ea-8de0-ab44bcea6d6e.png)
> 
> 도커를 재시작한 후 다시 실행해도 똑같은데 다른 해결방법이 있을까요?

**Comment by ratsgo** [comment]
@ldahee 님 안녕하세요. 제가 너무 늦게 답을 드린 건 아닌지 모르겠네요.
해당 내용은 다음 이슈에서 제기된 바 있는데요. 

- https://github.com/ratsgo/embedding/issues/69

제가 튜토리얼 페이지 업데이트를 깜빡하고 있었습니다. 죄송합니다.
바로 업데이트 해두겠습니다.

감사합니다.
