### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by jiayana** [ratsgo/embedding#95]
안녕하세요.

많은 정보를 공유해주셔서 항상 감사하게 생각하고 있습니다.

현재 models/tune_utils.py를 활용하여 파인튜닝을 수행하고 있습니다.
그런데, 다음과 같은 에러가 발생하여 글을 작성합니다.

/usr/local/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
Traceback (most recent call last):
  File "models/tune_utils.py", line 4, in <module>
    from tensorflow.contrib import nccl
ImportError: cannot import name 'nccl' from 'tensorflow_core.contrib' (/home/myname/.local/lib/python3.7/site-packages/tensorflow_core/contrib/__init__.py)
============================================================

현재, tensorflow 버전은 '1.15.2'입니다.
검색해보니 tensorflow.contrib 관련하여 1.13 버전 이상이면 사용 가능하다고 하던데, 학습이 되지 않습니다.
혹시 수행할 때 환경의 버전이나 유의할 사항이 알 수 있을까요?

**Comment by ratsgo** [comment]
@jiayana 님 안녕하세요. 해당 오류는 nccl 라이브러리 때문으로 보이는데요.
일단 다음 이슈를 참고하시면 좋을 것 같습니다.

- https://github.com/ratsgo/embedding/issues/27#issuecomment-539348797

문제가 계속 발생한다면 이 이슈에 더 질문해 주시면 제가 아는 한 답변해 드리겠습니다.
