### ISSUE TITLE
2쇄 127페이지 오타 제보 및 코드 4-5 코사인 유사도 상위 단어 목록 체크 코드 실행 오류 관련

### ISSUE THREAD

**Issue by ParkIlseop** [ratsgo/embedding#96]
안녕하세요?
자연어 처리를 독학하면서 한국어 임베딩 책을 유용하게 보고 있습니다. 

word2vec 연습 중에 책에 있는 그대로 타이핑했는데 코드 실행 오류가 떠서 질문 남깁니다. 

2쇄 127페이지 4-5 코드이며, 

from models.word_eval import WordEmbeddingEvaluator

해당 코드 실행했을 때
No module named 'models'

이러한 오류가 뜹니다. (앞 페이지 4-3 코드 실행하면서 gensim은 설치가 되었고요)
어떤 문제인지 찾아 보고 있지만, 잘 해결이 되지 않아 질문 드립니다. 

아울러 코드 4-5 위에 있는 본문 설명 중에 오타가 있는 것 같아 제보 드립니다. 

"코드 4-5를 실행하면 기준 단어와 코사인 유사도가 가장 높은 단어 10개와 그 유사도가 출력된다."

10개가 아니라 5개 아닌지 확인해 주시면 될 것 같습니다. 

감사합니다.

**Comment by ratsgo** [comment]
@ParkIlseop 님 안녕하세요. 부족한 책인데 관심 가져주셔서 감사드립니다.

> word2vec 연습 중에 책에 있는 그대로 타이핑했는데 코드 실행 오류가 떠서 질문 남깁니다.
2쇄 127페이지 4-5 코드이며,
from models.word_eval import WordEmbeddingEvaluator
해당 코드 실행했을 때
No module named 'models'
이러한 오류가 뜹니다. (앞 페이지 4-3 코드 실행하면서 gensim은 설치가 되었고요)
어떤 문제인지 찾아 보고 있지만, 잘 해결이 되지 않아 질문 드립니다.

도서에서 제공하고 있는 도커 환경에서 수행한 결과 다음과 같이 문제 없이 실행된 걸 확인할 수 있었습니다.

<img width="500" alt="스크린샷 2020-07-11 오후 12 40 51" src="https://user-images.githubusercontent.com/26211652/87215676-c612d600-c373-11ea-9a57-35b0032f0161.png">

개발환경 설정에 어려움을 겪고 계시다면 도서에서 제공하는 도커 환경 사용을 추천해 드립니다:)

> 아울러 코드 4-5 위에 있는 본문 설명 중에 오타가 있는 것 같아 제보 드립니다.
"코드 4-5를 실행하면 기준 단어와 코사인 유사도가 가장 높은 단어 10개와 그 유사도가 출력된다."
10개가 아니라 5개 아닌지 확인해 주시면 될 것 같습니다.

해당 내용은 오타가 맞습니다. 3쇄 이후에는 수정 반영되어 있는데요. 다시 한번 체크해 보겠습니다.
혼란을 드려 죄송하고, 꼼꼼하게 읽어주셔서 진심으로 감사드립니다.
