### ISSUE TITLE
참고 문헌은 어디서 확인할 수 있을까요? 

### ISSUE THREAD

**Issue by dbwodlf3** [ratsgo/embedding#97]
책의 339 페이지에 참고문헌이 나옵니다.
강필성(2017). IME653 : 비정형데이터분석, 고려대학교
이건 논문이 아니라 수업인걸까요?
논문을 찾아서 봐보고 싶은데 찾을 수가 없어서 질문 드립니다.

ㅠㅠ.

**Comment by ratsgo** [comment]
@dbwodlf3 님 관심 가져주셔서 감사드립니다.
말씀하신 `강필성(2017). IME653 : 비정형데이터분석, 고려대학교`는 수업입니다.
수업 동영상과 수업 자료는 github에 공개돼 있습니다. 다음과 같습니다.

https://github.com/pilsung-kang/text-analytics

도움이 되셨으면 좋겠습니다!
