### ISSUE TITLE
3쇄 217p 2번째 문단 첫번째 줄

### ISSUE THREAD

**Issue by Usurper47** [ratsgo/embedding#98]
쓰인다. 쓰인다. -> 쓰인다.

그리고 오탈자 관련해서 2쇄에는 어디까지 반영되었고, 3쇄에는 어디까지 반영되었고.. 이런 정보가 어디 있을까요?

**Comment by ratsgo** [comment]
> 쓰인다. 쓰인다. -> 쓰인다.

@Usurper47 님 예리한 지적 감사드립니다. 이후 종이책과 전자책에 반영해 두겠습니다.

> 그리고 오탈자 관련해서 2쇄에는 어디까지 반영되었고, 3쇄에는 어디까지 반영되었고.. 이런 정보가 어디 있을까요?

[정오표](https://ratsgo.github.io/embedding/notice.html)가 있기는 합니다만, 초판 초쇄 대비 틀린 점을 기록해 둔 것입니다. 말씀하신 것처럼 쇄별로 반영된 정보가 독자 여러분께 유의미할 것으로 판단되는 만큼 출판사와 상의해 관련 정보를 별도 이슈에 공지하겠습니다. 

의견 진심으로 감사드립니다.
